project_id = "krdwypftyokqsffxoobk"

[functions.fetch-models]
verify_jwt = false

[functions.chat]
verify_jwt = true

[functions.realtime-token]
verify_jwt = true

[functions.parse-document]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.rag-search]
verify_jwt = true