-- Pack 17: Healthcare Compliance Standards (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'HIPAA Compliance Audit', 'Conduct a comprehensive HIPAA compliance audit for our healthcare application. Review patient data handling, encryption protocols, access controls, audit logging, data retention policies, and breach notification procedures. Identify gaps against HIPAA Privacy and Security Rules. Provide detailed recommendations for achieving full compliance including technical controls, administrative safeguards, physical security measures, and staff training requirements. Include a timeline for remediation and ongoing compliance monitoring procedures.', 0 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'GDPR Health Data Processing', 'Design a GDPR-compliant data processing framework for handling health information. Include lawful basis for processing, data subject rights implementation (access, rectification, erasure, portability), consent management workflows, data protection impact assessments, privacy by design principles, breach notification procedures, and third-party processor agreements. Ensure special category data protections for health information. Provide documentation templates and technical implementation guidelines using Australian and international best practises.', 1 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Medical Device Software Standards', 'Develop software following IEC 62304 medical device software lifecycle standards. Include risk management per ISO 14971, software safety classification, requirements specification, architectural design, detailed design documentation, unit and integration testing protocols, verification and validation procedures, and maintenance planning. Address cybersecurity requirements per FDA guidance. Provide traceability matrices linking requirements to design, code, and test cases using industry-recognised methodologies.', 2 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Clinical Trial Data Management', 'Design a clinical trial data management system compliant with ICH-GCP, FDA 21 CFR Part 11, and CDISC standards. Include electronic data capture, source data verification, query management, audit trails, electronic signatures, data validation rules, and regulatory submission datasets (SDTM, ADaM). Implement access controls based on study roles, data encryption, and secure transmission protocols. Provide SOPs for data management activities and validation documentation using Australian regulatory frameworks.', 3 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Telehealth Privacy Framework', 'Create a privacy and security framework for telehealth services. Address video consultation encryption, patient identity verification, informed consent for remote services, prescription management, integration with electronic health records, session recording policies, and emergency protocols. Include compliance with telehealth regulations, professional licensing requirements, cross-border care considerations, and accessibility standards. Provide technical specifications and clinical workflow integration guidelines using Australian healthcare standards.', 4 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Electronic Health Records Interoperability', 'Implement HL7 FHIR-based interoperability for electronic health records. Include patient demographics, clinical observations, medications, allergies, immunisations, diagnostic reports, and care plans. Design RESTful APIs with OAuth 2.0 authentication, implement SMART on FHIR for app integration, support bulk data export, and enable patient access APIs. Address data normalisation, terminology mapping (SNOMED CT, LOINC), and consent management for data sharing using Australian e-health standards.', 5 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Pharmaceutical Quality System', 'Design a computerised system for pharmaceutical manufacturing compliant with GMP, FDA 21 CFR Part 11, and EU Annex 11. Include batch record management, deviation tracking, change control, supplier qualification, equipment calibration, stability studies, and complaint handling. Implement electronic signatures, audit trails, system validation, and data integrity controls (ALCOA+ principles). Provide validation protocols (IQ, OQ, PQ) and ongoing compliance monitoring procedures using Australian TGA requirements.', 6 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Mental Health Platform Compliance', 'Build a mental health service platform addressing special compliance requirements. Include enhanced privacy protections for sensitive conditions, crisis intervention protocols, mandatory reporting workflows, informed consent for minors, therapist-patient communication security, appointment scheduling with privacy considerations, and integration with crisis support services. Address ethical guidelines for AI-assisted mental health tools and ensure accessibility for diverse populations using Australian mental health frameworks.', 7 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Laboratory Information System Standards', 'Develop a laboratory information system compliant with ISO 15189, CLIA, and CAP requirements. Include specimen tracking, test ordering, result reporting, quality control, proficiency testing, reference ranges, critical value notifications, and integration with analysers. Implement result validation workflows, delta checking, reflex testing rules, and audit trails. Address turnaround time monitoring, billing integration, and regulatory reporting using Australian pathology accreditation standards.', 8 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'
UNION ALL
SELECT id, 'Healthcare Cybersecurity Framework', 'Implement a cybersecurity framework for healthcare organisations based on NIST Cybersecurity Framework and HITRUST CSF. Include risk assessment, asset inventory, network segmentation, endpoint protection, vulnerability management, incident response, business continuity, and disaster recovery. Address medical device security, secure remote access, ransomware protection, and security awareness training. Provide security policies, procedures, and compliance documentation using Australian healthcare cybersecurity guidelines.', 9 FROM prompt_packs WHERE name = 'Healthcare Compliance Standards';

-- Pack 18: Mobile App Development (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Cross-Platform Mobile Architecture', 'Design a cross-platform mobile application architecture using React Native or Flutter. Include navigation structure, state management strategy (Redux, MobX, Provider), API integration patterns, offline-first capabilities with local data synchronisation, push notification handling, deep linking, biometric authentication, and app update mechanisms. Address platform-specific customisations, performance optimisation, and code sharing strategies. Provide folder structure, coding standards, and testing approaches for both iOS and Android using modern development practises.', 0 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile App Performance Optimisation', 'Optimise mobile application performance across devices and network conditions. Profile and improve app startup time, screen rendering, memory usage, battery consumption, and network efficiency. Implement lazy loading, image optimisation, code splitting, and efficient list rendering. Address background task management, location services optimisation, and sensor data handling. Provide monitoring and analytics integration to track performance metrics in production using Australian mobile network considerations.', 1 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Progressive Web App Implementation', 'Build a Progressive Web App with native-like capabilities. Implement service workers for offline functionality, app manifest for installability, push notifications, background sync, and cache strategies. Design responsive layouts for all screen sizes, add touch gestures, implement app shortcuts, and enable platform-specific features through Web APIs. Address iOS Safari limitations and provide fallbacks. Include performance budgets and Core Web Vitals optimisation using modern PWA standards.', 2 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile Authentication & Security', 'Implement secure authentication for mobile applications. Include OAuth 2.0 / OpenID Connect integration, biometric authentication (Face ID, Touch ID, fingerprint), secure token storage using keychain/keystore, certificate pinning, API request signing, and session management. Address jailbreak/root detection, code obfuscation, secure local storage, and protection against reverse engineering. Implement multi-factor authentication and provide security best practises documentation using Australian cybersecurity frameworks.', 3 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile CI/CD Pipeline', 'Set up continuous integration and deployment pipeline for mobile apps. Configure automated builds for iOS (Xcode) and Android (Gradle), code signing, automated testing (unit, integration, UI), code quality checks, and distribution to TestFlight and Google Play. Implement beta testing workflows, crash reporting integration, and release management. Address versioning strategies, rollback procedures, and feature flag management. Provide configuration for popular CI/CD platforms using industry-standard tools.', 4 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile Offline-First Architecture', 'Design an offline-first mobile application with seamless online/offline transitions. Implement local database (SQLite, Realm, WatermelonDB), data synchronisation strategies (conflict resolution, incremental sync), queue management for offline actions, and optimistic UI updates. Address attachment/media caching, background sync when connection restored, and sync status indicators. Provide data migration strategies and handle edge cases like partial syncs using robust architectural patterns.', 5 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile AR Integration', 'Integrate augmented reality features into mobile application using ARKit (iOS) or ARCore (Android). Implement marker-based or markerless AR, 3D object placement, face tracking, image recognition, and AR measurement tools. Address performance optimisation for AR rendering, handle device capability detection, and provide fallback experiences for unsupported devices. Include asset management for 3D models and provide user onboarding for AR features using current AR development standards.', 6 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile App Accessibility', 'Ensure mobile application meets accessibility standards (WCAG 2.1 Level AA). Implement screen reader support, dynamic type sizing, high contrast modes, voice control, and reduced motion preferences. Provide alternative text for images, proper heading hierarchy, keyboard navigation, and focus management. Test with assistive technologies on both platforms, address colour contrast requirements, and ensure touch target sizes. Create accessibility testing checklist using Australian accessibility guidelines.', 7 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile Payment Integration', 'Integrate mobile payment solutions (Apple Pay, Google Pay, in-app purchases). Implement payment form with validation, tokenisation, 3D Secure authentication, and receipt generation. Handle payment method storage, recurring billing, refund processing, and payment webhooks. Address PCI DSS compliance, fraud detection integration, and regional payment methods. Provide error handling, transaction logging, and reconciliation procedures using Australian payment processing standards.', 8 FROM prompt_packs WHERE name = 'Mobile App Development'
UNION ALL
SELECT id, 'Mobile App Analytics & Monitoring', 'Implement comprehensive analytics and monitoring for mobile applications. Integrate analytics platforms (Firebase, Amplitude, Mixpanel), crash reporting (Crashlytics, Sentry), performance monitoring (APM), and user behaviour tracking. Set up custom events, user properties, conversion funnels, and A/B testing. Address privacy compliance (consent management, data anonymisation), implement session recording where appropriate, and create analytics dashboards. Provide data governance and retention policies using privacy-focused approaches.', 9 FROM prompt_packs WHERE name = 'Mobile App Development';