-- Pack 30: Legacy System Modernisation (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Legacy Assessment Framework', 'Conduct comprehensive assessment of legacy systems for modernisation. Include technical debt analysis, architecture review, code quality assessment, and dependency mapping. Design business value evaluation, risk assessment, and modernisation readiness. Address stakeholder interviews, documentation review, and system profiling. Implement scoring frameworks, prioritisation matrices, and recommendation reports. Provide assessment templates, interview guides, and analysis methodologies using legacy modernisation frameworks and Australian technology assessment standards.', 0 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Strangler Fig Pattern Implementation', 'Implement strangler fig pattern for gradual legacy replacement. Include functionality identification, routing layer design, incremental migration, and parallel running. Design anti-corruption layer, feature toggles, and rollback mechanisms. Address data synchronization, transaction boundaries, and testing strategies. Implement monitoring for both systems, cutover planning, and decommissioning procedures. Provide pattern implementation guides, architectural blueprints, and migration playbooks using modernisation patterns and Australian system migration standards.', 1 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Data Migration Strategy', 'Design data migration strategy for legacy modernisation. Include data profiling, quality assessment, mapping and transformation, and validation. Design incremental migration, dual-write patterns, change data capture, and synchronization. Address referential integrity, data cleanup, and cutover strategy. Implement migration testing, rollback procedures, and reconciliation. Provide migration frameworks, tooling selection, and quality assurance using data migration methodologies and Australian data governance standards.', 2 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Microservices Extraction', 'Extract microservices from monolithic legacy systems. Include bounded context identification, service boundary definition, dependency analysis, and extraction sequencing. Design API contracts, data ownership, and integration patterns. Address transaction management, consistency models, and deployment independence. Implement service scaffolding, migration validation, and rollback strategies. Provide extraction patterns, refactoring techniques, and governance frameworks using domain-driven design principles and Australian microservices standards.', 3 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Legacy API Wrapping', 'Wrap legacy systems with modern APIs for integration. Include API design, facade pattern implementation, protocol translation, and data transformation. Design error handling, rate limiting, caching, and monitoring. Address authentication/authorization adaptation, versioning, and documentation. Implement API gateway integration, legacy system protection, and deprecation planning. Provide API wrapping patterns, security hardening, and operational procedures using API modernisation best practises and Australian integration standards.', 4 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Code Refactoring Strategy', 'Plan systematic code refactoring for legacy systems. Include code smell identification, refactoring prioritisation, testing strategy, and incremental approach. Design extract method, extract class, consolidate conditional, and remove duplication. Address regression prevention, team skill development, and refactoring metrics. Implement automated refactoring tools, code review processes, and quality gates. Provide refactoring catalogues, safety techniques, and continuous improvement using clean code principles and Australian software quality standards.', 5 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Legacy Technology Stack Upgrade', 'Upgrade legacy technology stack components. Include dependency analysis, version compatibility assessment, breaking change identification, and upgrade sequencing. Design phased upgrades, compatibility layers, and testing strategies. Address framework migrations, library replacements, and infrastructure updates. Implement upgrade automation, rollback procedures, and validation testing. Provide upgrade playbooks, risk mitigation strategies, and team training using technology upgrade methodologies and Australian DevOps standards.', 6 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Legacy to Cloud Migration', 'Migrate legacy systems to cloud infrastructure. Include cloud readiness assessment, migration strategy selection (rehost, replatform, refactor), and workload analysis. Design cloud architecture, networking, security, and compliance. Address performance optimization, cost modeling, and operational changes. Implement migration waves, testing in cloud, and cutover planning. Provide cloud migration frameworks, landing zone design, and governance policies using cloud adoption frameworks and Australian cloud migration standards.', 7 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Testing Legacy Systems', 'Implement testing for legacy systems before and during modernisation. Include characterization testing, regression test creation, test coverage improvement, and automated testing. Design testing strategies for systems without tests, exploratory testing, and approval testing. Address golden master testing, snapshot testing, and property-based testing. Implement test harnesses, seam creation, and dependency breaking. Provide testing patterns for legacy code, tool recommendations, and quality metrics using legacy testing techniques and Australian quality assurance standards.', 8 FROM prompt_packs WHERE name = 'Legacy System Modernisation'
UNION ALL
SELECT id, 'Knowledge Transfer & Documentation', 'Capture and transfer knowledge from legacy systems. Include documentation archeology, code reading sessions, system mapping, and tacit knowledge extraction. Design knowledge artifacts (architecture diagrams, data dictionaries, runbooks), video documentation, and knowledge repositories. Address expert interviews, pair programming for knowledge transfer, and documentation standards. Implement continuous documentation, knowledge validation, and onboarding processes. Provide documentation templates, knowledge capture techniques, and transfer strategies using knowledge management principles and Australian documentation standards.', 9 FROM prompt_packs WHERE name = 'Legacy System Modernisation';