-- Packs 16-25 with 10 prompts each
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index) VALUES
-- Pack 16
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'HIPAA Compliance Implementation', 'Implement HIPAA-compliant systems. Include: 1) Protected health information handling, 2) Access controls, 3) Audit logging, 4) Data encryption, 5) Business associate agreements, 6) Breach notification procedures, 7) Risk assessment, 8) Training requirements. Provide compliance checklists using Australian spelling.', 2),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Medical Data Security', 'Secure medical data systems. Include: 1) Data classification, 2) Encryption standards, 3) Access management, 4) Authentication mechanisms, 5) Secure data transmission, 6) Data retention policies, 7) Disposal procedures, 8) Security monitoring. Provide security implementation using Australian spelling.', 3),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Clinical System Integration', 'Integrate clinical systems. Include: 1) HL7 FHIR implementation, 2) EHR integration, 3) Interoperability standards, 4) Data mapping, 5) Real-time synchronisation, 6) Error handling, 7) Testing procedures, 8) Compliance verification. Provide integration examples using Australian spelling.', 4),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Patient Portal Development', 'Build patient portals. Include: 1) Authentication and identity verification, 2) Medical record access, 3) Appointment scheduling, 4) Secure messaging, 5) Prescription management, 6) Test results viewing, 7) Bill payment, 8) Accessibility compliance. Provide portal features using Australian spelling.', 5),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Telemedicine Platform', 'Develop telemedicine solution. Include: 1) Video consultation, 2) Chat functionality, 3) File sharing, 4) E-prescribing, 5) Insurance verification, 6) Recording and storage, 7) Quality monitoring, 8) Regulatory compliance. Provide platform architecture using Australian spelling.', 6),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Medical Billing Systems', 'Design medical billing system. Include: 1) Claims processing, 2) Insurance integration, 3) Payment processing, 4) Coding accuracy, 5) Denial management, 6) Reporting, 7) Compliance tracking, 8) Patient statements. Provide billing workflows using Australian spelling.', 7),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Clinical Decision Support', 'Implement decision support systems. Include: 1) Clinical guidelines integration, 2) Alert systems, 3) Drug interaction checking, 4) Evidence-based recommendations, 5) Risk assessment, 6) Documentation, 7) Audit trails, 8) User feedback. Provide CDS examples using Australian spelling.', 8),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Healthcare Analytics', 'Build healthcare analytics platform. Include: 1) Data warehousing, 2) Quality metrics, 3) Population health analytics, 4) Predictive modelling, 5) Dashboard design, 6) Report generation, 7) Privacy protection, 8) Regulatory reporting. Provide analytics implementation using Australian spelling.', 9),
((SELECT id FROM prompt_packs WHERE name = 'Healthcare Compliance Standards'), 'Medical Device Integration', 'Integrate medical devices. Include: 1) Device connectivity protocols, 2) Data acquisition, 3) Real-time monitoring, 4) Alert systems, 5) Data storage, 6) Calibration tracking, 7) Regulatory compliance, 8) Error handling. Provide device integration using Australian spelling.', 10);