-- Construction Project Management prompts (all 10)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Project Estimation & Quoting', 'Create comprehensive project estimate for [construction project type] at [location]. Conduct site assessment documenting access constraints, services availability, ground conditions, neighbouring property considerations, and environmental factors. Develop scope of work breakdown structure with detailed task list, material specifications, labour requirements, equipment needs, and subcontractor packages. Calculate material quantities using take-offs from plans (concrete, steel, timber, cladding, fixtures) with waste factors and market price research. Estimate labour hours by trade (carpentry, plumbing, electrical, tiling) with appropriate productivity rates and award wage calculations. Price equipment requirements (scaffolding, cranes, formwork, tools) with hire vs purchase analysis. Obtain subcontractor quotes for specialist trades with scope verification and price comparison. Calculate project preliminaries (site establishment, temporary facilities, safety equipment, insurances, permits). Assess project risks and include appropriate contingency allowances. Apply overhead and profit margins appropriate to project complexity and market conditions. Present quote with clear inclusions/exclusions, payment schedule, variation procedures, and validity period. Include value engineering options, staging possibilities, and alternative material selections for client budget flexibility.', 1
FROM prompt_packs WHERE name = 'Construction Project Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Site Management Protocols', 'Establish comprehensive site management system for [construction project]. Create site establishment checklist including boundary fencing, site signage, amenities (toilets, lunch room), material storage areas, waste management zones, and services protection. Develop daily site management routine with pre-start meetings covering day''s activities, hazard identification, task allocation, and coordination between trades. Establish site diary documentation recording weather, workforce attendance, visitors, deliveries, work completed, issues encountered, and instructions given. Create quality inspection procedures at critical hold points with photographic documentation and sign-off requirements. Develop progress monitoring against program with early warning for delays and recovery strategies. Establish material management with delivery scheduling, storage protection, stock rotation, and waste minimisation. Create site communications protocol for client updates, consultant coordination, subcontractor briefings, and issue resolution. Develop defect management system with identification, recording, rectification scheduling, and verification procedures. Establish environmental management covering dust suppression, noise control, erosion/sediment control, and neighbour considerations. Create emergency response procedures for injuries, fires, hazardous material spills, and extreme weather. Include workforce management (inductions, toolbox talks, performance issues), visitor management (sign-in, PPE, escorting), and site security (after-hours access, material theft prevention, vandalism protection).', 2
FROM prompt_packs WHERE name = 'Construction Project Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Subcontractor Coordination', 'Design subcontractor coordination system for [construction project]. Develop subcontractor selection criteria including licensing verification, insurance currency, financial stability, previous performance, and capability assessment. Create comprehensive subcontract agreements covering scope definition, quality standards, program requirements, payment terms (progress claims, retention), variation procedures, defect liability, and termination clauses. Establish pre-start coordination meetings reviewing scope, site conditions, access arrangements, other trades interfaces, safety requirements, and quality expectations. Develop detailed program coordination showing trade sequences, lead times, critical path activities, and labour resource requirements with clash identification and resolution. Create weekly coordination meetings with look-ahead planning (2-4 weeks), progress review, issue resolution, and commitment scheduling. Establish site access protocols for multiple trades working simultaneously with workspace allocation and service access coordination. Develop quality interface management ensuring trades understand hand-over conditions and inspection requirements between packages. Create payment administration procedures with progress assessment, payment certification, and retention release aligned to contract milestones. Establish variation management with scope change documentation, quote requests, approval procedures, and contract sum updates. Develop performance monitoring with KPIs for safety, quality, program adherence, and relationship management. Include dispute resolution procedures, underperformance management escalation, and contract enforcement when necessary. Document lessons learned for future subcontractor selection and management improvement.', 3
FROM prompt_packs WHERE name = 'Construction Project Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'WHS Safety Compliance', 'Create comprehensive workplace health and safety management system for [construction site]. Develop site-specific safety plan addressing identified hazards (working at heights, electrical, excavation, plant operation, manual handling, hazardous materials, confined spaces) with control measures hierarchy. Establish site induction program covering emergency procedures, hazard awareness, PPE requirements, reporting obligations, and site rules with competency assessment. Create daily pre-start hazard identification process with toolbox talks, task-specific risk assessment (SWMS - Safe Work Method Statements), and control verification. Develop permit-to-work systems for high-risk activities (hot works, confined space entry, electrical isolation, excavation near services) with authorisation and monitoring procedures. Establish plant and equipment management including pre-start inspections, operator licensing verification, maintenance scheduling, and exclusion zones. Create scaffold and edge protection inspection regime with tagging systems and competent person certification. Develop hazardous materials management (asbestos, lead paint, chemical storage) with safety data sheets, handling procedures, and emergency response. Establish incident and near-miss reporting with investigation procedures, root cause analysis, corrective actions, and regulatory notification when required. Create safety inspection program with regular site walks, audit checklists, non-conformance recording, and corrective action tracking. Develop emergency response procedures including first aid provision, evacuation plans, emergency contacts, and rescue equipment. Include safety performance measurement, leading and lagging indicators, safety meetings, and continuous improvement culture development. Ensure compliance with WHS legislation, codes of practice, and principal contractor obligations.', 4
FROM prompt_packs WHERE name = 'Construction Project Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Quality Control Systems', 'Establish systematic quality management for [construction project]. Develop quality plan aligned to contract specifications defining inspection and test requirements, hold points requiring approval before proceeding, and documentation requirements. Create inspection and test plans (ITP) for each construction element specifying inspection stages, testing frequency, acceptance criteria, and responsible parties. Establish material approval procedures with submittal requirements, sample provision, testing protocols, and documentation before installation. Develop workmanship standards communication through method statements, mock-ups, and site demonstrations ensuring trades understand quality expectations. Create inspection documentation system with checklist completion, photographic evidence, non-conformance recording, and sign-off procedures. Establish hold point management requiring client/consultant approval before concealing work or proceeding with following stages. Develop non-conformance management with identification, impact assessment, rectification proposals, implementation, and verification procedures. Create quality records management maintaining material certificates, test results, inspection records, and compliance documentation for handover. Establish commissioning and testing procedures for services (electrical, hydraulic, mechanical, fire) with witness testing and certification. Develop defects management during construction with defect register, rectification scheduling, and verification before practical completion. Create pre-handover inspections with comprehensive defect identification (defects list), rectification program, and re-inspection scheduling. Establish practical completion procedures with statutory compliance verification, required documentation compilation, and client training on systems operation. Include warranty period defects management, final inspection for defects liability completion, and lessons learned documentation for continuous improvement. Ensure quality system compliance with Australian Standards, building codes, and project specifications.', 5
FROM prompt_packs WHERE name = 'Construction Project Management';