-- Accounting & Bookkeeping prompts
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Financial Statement Preparation', 'Prepare comprehensive financial statements for [business name] for the period ending [date]. Generate profit and loss statement with detailed revenue breakdown by product/service lines, cost of goods sold with inventory reconciliation, operating expenses categorised by department/function, EBITDA and NPBT calculations, and year-on-year variance analysis with explanatory notes. Create balance sheet showing current and non-current assets with depreciation schedules, current and non-current liabilities with ageing analysis, equity movements including retained earnings and owner contributions, and working capital ratios. Develop cash flow statement using indirect method showing operating, investing, and financing activities, reconciliation to bank balances, and cash flow adequacy analysis. Include comprehensive notes covering accounting policies, significant estimates and judgements, related party transactions, contingent liabilities, post-balance date events, and compliance with accounting standards (AASB). Provide management commentary on financial performance, key drivers, and outlook. Ensure all statements comply with Australian accounting standards and tax requirements.', 1
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Tax Planning Strategy', 'Develop a comprehensive tax planning strategy for [entity type] with annual income of [amount] for the financial year ending [date]. Analyse current tax position and effective tax rate, identify legitimate tax minimisation opportunities within ATO guidelines, evaluate income deferral strategies and timing considerations, assess deduction maximisation opportunities including often-missed deductions, review asset depreciation schedules and instant asset write-off eligibility, evaluate superannuation contribution strategies for tax effectiveness, analyse trust distribution strategies for family groups, assess company vs trust structure optimisation, review franking credit utilisation, evaluate capital gains tax minimisation strategies including CGT discount and small business concessions, assess research and development tax incentive eligibility, review fringe benefits tax implications and optimisation, evaluate GST strategies and supply categorisation, assess international tax implications if applicable, review Division 7A loan compliance, and develop year-end tax planning checklist with actionable items and deadlines. Include scenario modelling for different strategies with estimated tax savings and risk assessment. Ensure all recommendations comply with anti-avoidance provisions and maintain audit defensibility.', 2
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Audit Documentation Standards', 'Create a comprehensive audit file for [client name] covering [audit period]. Develop audit planning documentation including risk assessment, materiality calculations, audit strategy, and scope definition. Prepare internal control documentation and testing procedures, create substantive testing programs for all financial statement areas, document sampling methodologies and selections, record all audit evidence and working papers with clear cross-referencing, prepare lead schedules and supporting schedules for all balance sheet and income statement items, document management representations and confirmations, create analytical review documentation with variance explanations, prepare subsequent events review, document going concern assessment, create audit adjustments and reclassifications schedule, prepare summary of uncorrected misstatements, document fraud risk assessment and responses, create related party transaction documentation, prepare final audit memorandum with key findings and recommendations, and develop audit completion checklist. Ensure all working papers meet auditing standards (ASA), include clear reviewer sign-offs, maintain professional scepticism documentation, and support all audit conclusions with sufficient appropriate evidence. Include quality control review documentation and independence confirmations.', 3
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Account Reconciliation Procedures', 'Establish systematic reconciliation procedures for [business name] covering all balance sheet accounts. Create bank reconciliation process with daily/weekly/monthly frequency requirements, document unreconciled items investigation procedures, establish cut-off controls for accurate period allocation, develop accounts receivable reconciliation with aged debtors analysis and bad debt review, create accounts payable reconciliation with creditor statement matching and accrual verification, establish inventory reconciliation procedures with physical count protocols and variance investigation, develop fixed asset register reconciliation with depreciation verification, create loan and liability reconciliations with interest calculations and covenant compliance monitoring, establish intercompany account reconciliation for group structures, develop GST and tax account reconciliations with return preparation support, create employee entitlement reconciliations with award and superannuation verification, establish investment and equity account reconciliations, develop suspense and control account clearing procedures, create reconciliation sign-off and review protocols with materiality thresholds, and establish exception reporting and escalation procedures. Include monthly reconciliation calendar with responsibility assignments, standard reconciliation templates, and variance investigation thresholds requiring management attention.', 4
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Payroll Processing Framework', 'Design a comprehensive payroll processing system for [business name] with [number] employees. Establish employee onboarding procedures including TFN declaration, superannuation choice form, and banking details verification, create timekeeping and attendance recording protocols, develop pay calculation methodology covering ordinary hours, overtime, allowances, commissions, and bonuses, establish leave accrual and leave loading calculations compliant with awards/agreements, create deduction processing for PAYG tax, superannuation, salary sacrifice, and other approved deductions, develop payroll approval and review procedures before payment processing, establish payment methods (EFT, cheque) with security controls, create payslip generation and distribution processes complying with Fair Work requirements, develop superannuation guarantee calculation and payment procedures with quarterly compliance monitoring, establish Single Touch Payroll (STP) reporting integration, create payroll reconciliation procedures with general ledger and control accounts, develop termination payment calculations including unused leave entitlements and final pay requirements, establish payroll tax compliance for applicable states/territories, create Workers Compensation premium calculation and reporting, develop payroll audit trails and record retention, and establish year-end PAYG summaries and payment summary preparation. Include award interpretation procedures, modern award compliance checking, and superannuation guarantee amnesty considerations.', 5
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'GST and BAS Lodgement', 'Create a systematic GST and BAS lodgement procedure for [business name] reporting [monthly/quarterly]. Establish transaction coding guidelines for GST classification (GST-free, input-taxed, taxable), develop sales and purchase recording procedures with tax invoice requirements verification, create adjustment identification processes for private use, bad debts, and change in use, establish cash vs accrual reporting methodology understanding, develop input tax credit claiming procedures with substantiation requirements, create capital acquisitions adjustment calculations, establish fuel tax credit calculations if applicable, develop wine equalisation tax and luxury car tax calculations if applicable, create PAYG withholding reconciliation from payroll to BAS, establish PAYG instalments calculation and variation requests, develop fringe benefits tax instalments if applicable, create BAS preparation checklist with account reconciliation requirements, establish review and approval procedures before lodgement, develop lodgement tracking system with due dates and penalty avoidance, create payment arrangement procedures if cash flow constrained, establish activity statement record retention (5 years minimum), and develop ATO correspondence monitoring and response procedures. Include monthly GST reconciliation between accounts and BAS, annual GST adjustment review, and GST registration threshold monitoring. Ensure compliance with increasing digital economy GST rules.', 6
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Expense Categorisation System', 'Develop a comprehensive chart of accounts and expense categorisation system for [business type]. Create detailed expense categories aligned with ATO tax return schedules and BAS reporting requirements, establish sub-accounts for departmental and project tracking, develop coding guidelines with examples for common transactions, create rules for borderline items requiring judgement (repairs vs capital improvements, deductible vs non-deductible expenses), establish business vs private use allocation methodologies for motor vehicles, home office, and mixed-use assets, develop entertainment expense classification (deductible, 50% deductible, non-deductible) with FBT considerations, create capital expenditure identification and asset capitalisation thresholds, establish prepayment and accrual identification procedures, develop intercompany and related party transaction coding, create loan and financing cost allocation, establish cost allocation methodologies for overheads, develop project and job cost tracking structures, create coding validation rules to prevent errors, establish periodic review procedures for correct categorisation, and develop reporting hierarchies for management and statutory accounts. Include decision trees for complex categorisation scenarios, training materials for staff, and integration guidelines for bank feeds and automated transaction imports. Ensure alignment with activity-based costing principles and management reporting requirements.', 7
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Budgeting Framework Development', 'Create a comprehensive budgeting framework for [business name] for the period [financial year]. Establish budget preparation methodology (zero-based, incremental, or activity-based), develop revenue forecasting using historical trends, market analysis, and growth initiatives, create detailed expense budgets by department/cost centre with line-item justifications, establish capital expenditure budget with project prioritisation and ROI analysis, develop cash flow budget with monthly phasing and working capital requirements, create balance sheet budget showing projected financial position, establish budget assumption documentation covering inflation, growth rates, and market conditions, develop key performance indicators and targets, create budget approval and sign-off process, establish budget communication and training procedures, develop variance analysis reporting format with materiality thresholds, create flexible budget models for different scenarios (best case, likely case, worst case), establish rolling forecast update procedures (quarterly/monthly), develop budget vs actual tracking dashboards, create variance investigation and explanation procedures, establish remedial action protocols for adverse variances, and develop budget revision and reforecasting procedures. Include integration with strategic planning, investment evaluation criteria, and performance management systems. Create sensitivity analysis for key assumptions and contingency planning for downside scenarios.', 8
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Cash Flow Forecasting Model', 'Design a detailed cash flow forecasting model for [business name] covering [forecast period]. Create opening cash position reconciliation to bank accounts, develop sales receipts forecasting based on debtor days and collection patterns, establish expense payment projections using creditor terms and payment cycles, create payroll payment scheduling with superannuation and tax withholding, develop loan repayment schedules with principal and interest separation, establish capital expenditure payment timing, create tax payment forecasting including PAYG instalments, GST, and income tax, develop dividend or distribution payment planning, establish working capital movement calculations, create seasonal adjustment factors for cyclical businesses, develop scenario analysis for different sales and collection outcomes, establish early warning indicators for cash flow stress, create daily/weekly/monthly rolling forecasts, develop cash buffer and reserve requirements, establish line of credit utilisation planning, create payment prioritisation framework for cash constraints, develop supplier payment term negotiation strategies, and establish cash flow improvement initiatives identification. Include dashboard visualisation with trend analysis, variance explanation requirements, and integration with business intelligence tools. Create sensitivity analysis for key variables (sales volume, pricing, debtor days, creditor days) and liquidity ratio monitoring.', 9
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Financial Reporting Templates', 'Create a comprehensive suite of financial reporting templates for [business name] covering all stakeholder needs. Develop management accounts package including executive summary dashboard, detailed P&L with variance analysis and KPIs, balance sheet with working capital metrics, cash flow statement with banking covenant calculations, departmental P&L reports, project profitability analysis, and key ratio analysis (liquidity, efficiency, profitability, leverage). Create board reporting pack with strategic KPI tracking, financial performance summary, significant items explanation, outlook and forecast updates, and risk assessment updates. Develop external stakeholder reports for banks (covenant compliance certification, financial position updates), investors (ROI analysis, distribution calculations), and regulatory bodies (statutory lodgement requirements). Establish monthly management reporting calendar with responsibilities and deadlines, create report review and approval procedures with sign-off protocols, develop commentary and narrative requirements explaining results and trends, establish exception reporting thresholds requiring explanation, create data visualisation standards using charts and graphs, develop benchmarking reports comparing to industry standards and prior periods, and establish report distribution protocols with confidentiality controls. Include automated report generation procedures where possible, data source verification requirements, and continuous improvement feedback mechanisms. Ensure all reports support decision-making with actionable insights and forward-looking analysis.', 10
FROM prompt_packs WHERE name = 'Accounting & Bookkeeping';