-- Pack 27: Performance Optimization (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Web Performance Optimization', 'Optimise web application performance across all metrics. Include Core Web Vitals optimization (LCP, FID, CLS), critical rendering path, resource loading, and JavaScript optimization. Implement code splitting, tree shaking, lazy loading, and prefetching. Address image optimization, font loading, and third-party script management. Provide performance budgets, monitoring setup, and continuous optimization processes using web performance best practises and Australian digital experience standards.', 0 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Database Query Optimization', 'Optimise database queries for performance and scalability. Include query analysis, indexing strategies, query rewriting, and execution plan optimization. Design denormalization strategies, materialized views, and caching layers. Address N+1 query problems, connection pooling, and batch operations. Implement query monitoring, slow query identification, and optimization tracking. Provide optimization guidelines, index strategy, and capacity planning using database performance tuning principles and Australian data management standards.', 1 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'API Performance Tuning', 'Tune API performance for low latency and high throughput. Include response time optimization, payload optimization, compression, and caching strategies. Design pagination, filtering, and field selection. Address rate limiting, connection reuse, and load balancing. Implement API monitoring, SLA tracking, and performance testing. Provide API optimization patterns, caching policies, and scaling strategies using API design best practises and Australian digital service standards.', 2 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Frontend Build Optimization', 'Optimise frontend build process and bundle size. Include webpack/vite configuration, code splitting strategies, module federation, and chunk optimization. Design asset optimization pipeline, source map configuration, and build caching. Address tree shaking effectiveness, duplicate dependency elimination, and polyfill optimization. Implement build time monitoring, bundle analysis, and size budgets. Provide build optimization checklist, configuration templates, and tooling recommendations using modern frontend build practises and Australian web development standards.', 3 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Caching Strategy Implementation', 'Design comprehensive caching strategy across application layers. Include browser caching, CDN caching, application caching, and database caching. Implement cache invalidation strategies, cache warming, and cache hierarchies. Address cache-aside pattern, write-through caching, and read-through caching. Design cache key strategies, TTL configuration, and cache consistency. Provide caching decision matrix, monitoring dashboards, and troubleshooting guides using caching architectural patterns and Australian infrastructure standards.', 4 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Memory Optimization Techniques', 'Optimise memory usage to prevent leaks and reduce footprint. Include memory profiling, leak detection, garbage collection tuning, and object pooling. Design efficient data structures, memory-aware algorithms, and resource disposal. Address circular references, event listener cleanup, and closure optimization. Implement memory monitoring, heap analysis, and alert thresholds. Provide memory optimization patterns, debugging techniques, and best practises using application performance management principles and Australian software engineering standards.', 5 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Network Performance Optimization', 'Optimise network performance for faster data transfer. Include HTTP/2 and HTTP/3 adoption, connection optimization, request reduction, and compression. Design resource hints (preconnect, prefetch, preload), multiplexing, and server push. Address latency reduction, CDN optimization, and edge computing. Implement network monitoring, waterfall analysis, and geographic performance testing. Provide network optimization checklist, protocol selection guidance, and infrastructure recommendations using network performance principles and Australian connectivity standards.', 6 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Mobile Performance Optimization', 'Optimise mobile application performance across devices. Include app startup time, frame rate optimization, battery consumption, and network efficiency. Design background task optimization, memory management, and storage efficiency. Address low-end device support, offline performance, and progressive enhancement. Implement performance profiling, device lab testing, and real-user monitoring. Provide mobile-specific optimization patterns, device targeting strategy, and performance budgets using mobile development best practises and Australian mobile standards.', 7 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Server-Side Performance Tuning', 'Tune server-side performance for scalability and efficiency. Include application server configuration, worker process optimization, thread pool tuning, and resource limits. Design asynchronous processing, queue management, and background jobs. Address connection pooling, keepalive settings, and timeout configuration. Implement server monitoring, profiling, and load testing. Provide server optimization guidelines, configuration templates, and scaling strategies using server performance tuning principles and Australian infrastructure standards.', 8 FROM prompt_packs WHERE name = 'Performance Optimization'
UNION ALL
SELECT id, 'Performance Monitoring & Observability', 'Implement performance monitoring and observability. Include Real User Monitoring (RUM), Synthetic monitoring, Application Performance Monitoring (APM), and infrastructure monitoring. Design performance dashboards, alerting rules, and anomaly detection. Address performance budgets, SLA tracking, and regression detection. Implement distributed tracing, profiling, and log correlation. Provide monitoring strategy, tool selection, and incident response using observability best practises and Australian operational standards.', 9 FROM prompt_packs WHERE name = 'Performance Optimization';

-- Pack 28: Business Process Automation (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Workflow Automation Design', 'Design workflow automation for business processes. Include process mapping, automation opportunity identification, decision logic, and exception handling. Implement approval workflows, notification systems, escalation rules, and SLA tracking. Address human-in-the-loop scenarios, parallel processing, and conditional branching. Design workflow monitoring, audit trails, and performance metrics. Provide workflow templates, best practises, and tool selection using business process management principles and Australian operational excellence frameworks.', 0 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Robotic Process Automation (RPA)', 'Implement RPA for repetitive task automation. Include process assessment for RPA suitability, bot development, exception handling, and orchestration. Design attended vs unattended bots, bot scheduling, and credential management. Address scalability, bot monitoring, and maintenance. Implement bot governance, version control, and testing strategies. Provide RPA framework selection, development standards, and ROI measurement using RPA best practises and Australian automation standards.', 1 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Document Processing Automation', 'Automate document processing using OCR and intelligent extraction. Include document classification, data extraction, validation rules, and exception handling. Design template-based and AI-based extraction, quality assurance workflows, and system integration. Address document formats, handwriting recognition, and accuracy improvement. Implement processing pipelines, monitoring dashboards, and continuous learning. Provide automation frameworks, accuracy metrics, and human review procedures using document automation technologies and Australian data processing standards.', 2 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Email Automation Systems', 'Build email automation systems for communication workflows. Include trigger-based emails, drip campaigns, personalisation, and segmentation. Design email templates, dynamic content, A/B testing, and send time optimization. Address deliverability, spam compliance, unsubscribe management, and bounce handling. Implement email analytics, performance tracking, and list hygiene. Provide email marketing automation, transactional email systems, and best practises using email marketing platforms and Australian anti-spam regulations.', 3 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Integration Automation', 'Automate system integrations using iPaaS and middleware. Include integration patterns, data transformation, error handling, and retry logic. Design API integrations, file-based integrations, event-driven integrations, and batch processing. Address data mapping, validation rules, and duplicate prevention. Implement integration monitoring, logging, and alerting. Provide integration architecture, platform selection, and governance using integration design patterns and Australian data exchange standards.', 4 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Chatbot Automation', 'Develop chatbot automation for customer service and internal operations. Include intent recognition, entity extraction, dialogue management, and natural language understanding. Design fallback handling, human handoff, context management, and multi-turn conversations. Address multi-channel deployment, personalization, and continuous learning. Implement chatbot analytics, conversation design, and testing strategies. Provide chatbot frameworks, best practises, and success metrics using conversational AI principles and Australian customer service standards.', 5 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Data Synchronization Automation', 'Automate data synchronization across systems. Include bidirectional sync, conflict resolution, incremental updates, and real-time replication. Design data transformation pipelines, validation rules, and error recovery. Address master data management, data quality, and audit logging. Implement sync monitoring, reconciliation checks, and failure alerts. Provide sync architecture, platform selection, and data governance using data integration patterns and Australian data management frameworks.', 6 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Report Generation Automation', 'Automate report generation and distribution. Include data collection, aggregation, calculation logic, and formatting. Design scheduled reports, on-demand reports, parameterised reports, and interactive dashboards. Address multiple output formats, distribution lists, and access control. Implement report caching, incremental refresh, and performance optimization. Provide reporting frameworks, template design, and governance using business intelligence automation and Australian reporting standards.', 7 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Compliance Automation', 'Automate compliance monitoring and reporting. Include regulatory requirement tracking, control automation, evidence collection, and audit trail generation. Design policy enforcement, violation detection, remediation workflows, and management reporting. Address continuous compliance monitoring, risk scoring, and exception management. Implement compliance dashboards, attestation workflows, and documentation management. Provide compliance frameworks, automation strategies, and audit preparation using GRC platforms and Australian regulatory compliance standards.', 8 FROM prompt_packs WHERE name = 'Business Process Automation'
UNION ALL
SELECT id, 'Testing Automation Framework', 'Build testing automation beyond functional tests. Include test data generation, environment provisioning, deployment automation, and results reporting. Design smoke test automation, regression suite scheduling, and cross-environment testing. Address test orchestration, parallel execution, and resource management. Implement test result analytics, flaky test management, and continuous improvement. Provide automation frameworks, CI/CD integration, and quality metrics using test automation principles and Australian quality assurance standards.', 9 FROM prompt_packs WHERE name = 'Business Process Automation';