-- Pack 19: Test Automation Strategies (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'End-to-End Testing Framework', 'Design a comprehensive end-to-end testing framework using Cypress, Playwright, or Selenium. Include test architecture, page object model implementation, test data management, environment configuration, and reporting. Implement visual regression testing, API mocking, authentication handling, and cross-browser testing. Address flaky test prevention, parallel execution, and CI/CD integration. Provide coding standards, reusable utilities, and maintenance strategies using modern testing practises.', 0 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'API Testing Automation', 'Create an automated API testing suite using Postman, REST Assured, or similar tools. Include functional tests, contract testing, performance testing, security testing, and data validation. Implement test data generation, environment variables, pre-request scripts, and assertion libraries. Design negative test scenarios, boundary value testing, and error handling validation. Integrate with CI/CD pipeline and provide API documentation validation using Australian software quality standards.', 1 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Unit Testing Best Practises', 'Establish unit testing standards for the codebase using Jest, Mocha, JUnit, or pytest. Include test coverage targets, mocking strategies, test isolation, and assertion patterns. Implement test fixtures, parameterised tests, and asynchronous testing. Address testing pure functions, class methods, hooks, and complex logic. Provide refactoring guidelines for testability, test naming conventions, and documentation. Integrate coverage reporting and quality gates using TDD principles.', 2 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Performance Testing Strategy', 'Design a performance testing strategy using JMeter, Gatling, or k6. Include load testing, stress testing, spike testing, endurance testing, and scalability testing. Define performance baselines, SLAs, and acceptance criteria. Implement realistic user scenarios, think times, and data variation. Address bottleneck identification, resource monitoring, and result analysis. Provide test environment requirements and production-like data generation using performance engineering methodologies.', 3 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Mobile Test Automation', 'Implement mobile test automation using Appium, Detox, or Espresso/XCUITest. Include real device and emulator testing, gesture handling, native and hybrid app support, and platform-specific features. Design test suites for functional testing, regression testing, and smoke testing. Address device farm integration, parallel execution across devices, and screenshot comparison. Provide device capability management and mobile-specific test patterns using cross-platform testing approaches.', 4 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Test Data Management', 'Create a test data management strategy for automated testing. Include synthetic data generation, data masking for sensitive information, test data refresh procedures, and data subset creation. Implement database seeding, API-based data setup, and data cleanup after tests. Address data privacy compliance, referential integrity, and realistic data scenarios. Provide tools for data versioning and environment-specific data sets using secure data handling practises.', 5 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Visual Regression Testing', 'Implement visual regression testing using Percy, Chromatic, or BackstopJS. Include baseline image capture, diff detection, responsive design testing, and cross-browser visual validation. Design test scenarios for UI components, full pages, and dynamic content. Address false positive reduction, threshold configuration, and approval workflows. Integrate with component libraries and design systems. Provide maintenance strategies for baseline updates using visual testing best practises.', 6 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Security Testing Automation', 'Automate security testing using OWASP ZAP, Burp Suite, or Snyk. Include vulnerability scanning, dependency checking, SQL injection testing, XSS detection, authentication bypass testing, and API security validation. Implement automated security test cases for OWASP Top 10 vulnerabilities, configuration security checks, and secrets detection. Address false positive management, severity classification, and remediation tracking. Integrate with CI/CD and security dashboards using DevSecOps principles.', 7 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Accessibility Testing Automation', 'Automate accessibility testing using axe-core, Pa11y, or Lighthouse. Include WCAG 2.1 compliance checks, keyboard navigation testing, screen reader compatibility, colour contrast validation, and semantic HTML verification. Implement automated tests for ARIA attributes, focus management, and alternative text. Address dynamic content accessibility and form validation. Provide manual testing checklists for scenarios requiring human judgement using Australian accessibility standards.', 8 FROM prompt_packs WHERE name = 'Test Automation Strategies'
UNION ALL
SELECT id, 'Continuous Testing Pipeline', 'Design a continuous testing pipeline integrated with CI/CD. Include automated test triggering on code commits, parallel test execution, test result reporting, and quality gates. Implement test prioritisation, flaky test detection and quarantine, and historical trend analysis. Address smoke tests for deployments, regression test suites, and production monitoring tests. Provide dashboard visualisation, notifications, and test automation metrics using modern DevOps practises.', 9 FROM prompt_packs WHERE name = 'Test Automation Strategies';

-- Pack 20: Data Analytics & Reporting (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Business Intelligence Dashboard', 'Design interactive business intelligence dashboards using Tableau, Power BI, or similar tools. Include KPI visualisations, trend analysis, drill-down capabilities, and filtering options. Implement data refresh schedules, alerting for threshold breaches, and role-based access control. Address data source connections, data transformation, and calculated measures. Provide user training materials and dashboard governance guidelines using data visualisation best practises and Australian business reporting standards.', 0 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'ETL Pipeline Development', 'Build an ETL (Extract, Transform, Load) pipeline using Apache Airflow, Talend, or AWS Glue. Include data extraction from multiple sources, data cleaning and transformation logic, data quality validation, error handling, and incremental loading. Implement scheduling, monitoring, alerting, and retry mechanisms. Address schema evolution, data lineage tracking, and performance optimisation. Provide documentation and runbooks for pipeline maintenance using modern data engineering practises.', 1 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'Predictive Analytics Model', 'Develop predictive analytics models using Python (scikit-learn, pandas) or R. Include data exploration, feature engineering, model selection (regression, classification, clustering), training and validation, and performance evaluation. Implement cross-validation, hyperparameter tuning, and model interpretability. Address overfitting prevention, bias detection, and production deployment. Provide model documentation, versioning, and monitoring strategies using machine learning best practises and Australian data science standards.', 2 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'Real-Time Analytics Platform', 'Design a real-time analytics platform using Apache Kafka, Spark Streaming, or AWS Kinesis. Include event ingestion, stream processing, windowing operations, and real-time aggregations. Implement exactly-once semantics, state management, and scalability. Address late-arriving data, out-of-order events, and backpressure handling. Provide monitoring dashboards, alerting, and operational runbooks using stream processing architectural patterns and Australian data infrastructure standards.', 3 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'Customer Segmentation Analysis', 'Perform customer segmentation analysis using clustering algorithms (K-means, hierarchical clustering, DBSCAN). Include RFM analysis (Recency, Frequency, Monetary), behavioural segmentation, demographic segmentation, and predictive segments. Implement segment profiling, visualisation, and actionable insights. Address segment stability over time, validation metrics, and business interpretation. Provide segment activation strategies and measurement frameworks using marketing analytics methodologies and Australian consumer insights.', 4 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'Data Lake Architecture', 'Design a data lake architecture using AWS S3, Azure Data Lake, or Google Cloud Storage. Include raw data ingestion, data cataloguing with metadata management, data zones (raw, curated, consumption), and access patterns. Implement data governance, quality monitoring, and lifecycle policies. Address schema-on-read approaches, data discovery, and query performance. Provide security controls, cost optimisation, and migration strategies using modern data lake design patterns and Australian data management frameworks.', 5 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'Financial Reporting Automation', 'Automate financial reporting processes including P&L statements, balance sheets, cash flow reports, and variance analysis. Include data consolidation from multiple sources, reconciliation checks, calculations of financial ratios, and compliance with accounting standards. Implement audit trails, version control, and approval workflows. Address period closing automation, budget vs actual comparisons, and forecasting. Provide report templates and distribution mechanisms using Australian financial reporting standards.', 6 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'A/B Testing Framework', 'Implement an A/B testing framework for product experimentation. Include experiment design, sample size calculation, random assignment, metric tracking, and statistical significance testing. Implement multi-variant testing, sequential testing, and Bayesian approaches. Address novelty effects, interaction effects, and segment-level analysis. Provide experiment documentation templates, result interpretation guidelines, and decision frameworks using experimental design methodologies and Australian digital analytics standards.', 7 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'Data Quality Monitoring', 'Design a data quality monitoring system to ensure analytics reliability. Include completeness checks, accuracy validation, consistency verification, timeliness monitoring, and uniqueness constraints. Implement data profiling, anomaly detection, and automated alerts. Address root cause analysis, data quality scorecards, and remediation workflows. Provide data quality rules documentation, ownership assignments, and continuous improvement processes using data governance frameworks and Australian data quality standards.', 8 FROM prompt_packs WHERE name = 'Data Analytics & Reporting'
UNION ALL
SELECT id, 'Operational Analytics Platform', 'Build an operational analytics platform for real-time business monitoring. Include system health metrics, transaction monitoring, user activity tracking, and operational KPIs. Implement alerting for SLA breaches, automated incident detection, and root cause analysis. Address log aggregation, metric collection, and correlation analysis. Provide operational dashboards, anomaly detection, and capacity planning capabilities using observability best practises and Australian operational excellence frameworks.', 9 FROM prompt_packs WHERE name = 'Data Analytics & Reporting';