-- CFO Pack - All 10 prompts
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Financial Performance Dashboard', 'Design a comprehensive executive financial dashboard for [COMPANY_NAME] providing real-time visibility of key financial metrics. Include revenue analysis by product line, region, and customer segment. Display EBITDA, cash flow, working capital, and profitability trends. Incorporate variance analysis comparing actual vs budget and prior year. Add key ratios including ROI, current ratio, debt-to-equity, and days sales outstanding. Implement drill-down capabilities and automated alerts for threshold breaches. Provide commentary templates explaining significant variances and recommended actions. Include forecast accuracy tracking and scenario comparison tools.', 1
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Annual Budget Development Process', 'Develop a comprehensive annual budget for [COMPANY_NAME] for FY[YEAR] incorporating strategic objectives and growth targets. Create detailed templates for all departments including revenue projections, operating expenses, capital expenditure, and headcount planning. Build bottom-up and top-down budget models with variance reconciliation. Include sensitivity analysis for key assumptions (sales growth, pricing, costs). Develop budget submission timeline, review process, and approval workflows. Create quarterly reforecasting methodology and variance reporting framework. Address foreign exchange impacts, commodity price risks, and market condition scenarios. Include board presentation materials.', 2
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Cash Flow Forecasting Model', 'Build a sophisticated 13-week cash flow forecast model for [COMPANY_NAME] with daily granularity. Include all cash inflows from customer receipts by due date, and outflows including payroll, supplier payments, tax obligations, and loan repayments. Model working capital movements including inventory build and accounts receivable collection patterns. Incorporate seasonality factors and growth assumptions. Develop scenario models for best case, base case, and worst case. Identify potential funding gaps and recommend solutions including facility drawdowns, payment term negotiations, or asset sales. Include covenant compliance monitoring and banking relationship management notes.', 3
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Cost Reduction Initiative Analysis', 'Analyse cost structure of [COMPANY_NAME] and identify opportunities to reduce operating expenses by [TARGET]% without compromising growth or quality. Conduct detailed cost centre analysis including personnel costs, facilities, technology, marketing, and professional services. Benchmark against industry standards and competitors. Develop business cases for each initiative including savings calculations, implementation costs, timeline, and risk assessment. Prioritise initiatives by ROI and implementation difficulty. Address change management requirements and stakeholder communication. Include ongoing monitoring metrics and realisation tracking methodology. Consider both quick wins and structural changes.', 4
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'M&A Financial Due Diligence', 'Conduct comprehensive financial due diligence on target company [TARGET_NAME] for potential acquisition. Analyse 3-5 years of financial statements including quality of earnings assessment. Review revenue recognition policies, working capital trends, debt obligations, and off-balance sheet items. Assess sustainability of EBITDA and identify normalisation adjustments. Evaluate tax positions, contingent liabilities, and related party transactions. Analyse customer concentration, contract terms, and revenue retention. Identify synergy opportunities and integration costs. Prepare detailed financial model incorporating acquisition financing, earn-out calculations, and ROI analysis. Highlight deal-breakers and key negotiation points.', 5
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Financial Systems Implementation', 'Plan and manage implementation of new [SYSTEM_NAME] financial system for [COMPANY_NAME] replacing legacy systems. Develop project plan including requirements gathering, vendor selection, data migration strategy, and user acceptance testing. Design chart of accounts, cost centre structure, and workflow approvals aligned to organisational structure. Plan integration with existing systems including CRM, inventory, and payroll. Address data governance, security controls, and audit trail requirements. Create change management program including training materials and support resources. Define success metrics, project governance, and risk mitigation strategies. Include post-implementation review process.', 6
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Board Financial Reporting Package', 'Prepare comprehensive board financial report for [COMPANY_NAME] for period ending [DATE]. Include executive summary highlighting key financial achievements, challenges, and outlook. Present consolidated financial statements with management commentary explaining material variances. Provide detailed analysis of revenue performance, gross margin trends, and operating expense management. Include cash position, debt facilities, and covenant compliance. Present capital expenditure analysis, major project updates, and forecast accuracy. Add strategic finance initiatives, risk assessment, and market condition impacts. Design clear visualisations and limit report to maximum 20 pages with supporting schedules available.', 7
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Working Capital Optimisation', 'Analyse and optimise working capital management for [COMPANY_NAME] to improve cash conversion cycle. Review accounts receivable including DSO analysis, aged trial balance, collection effectiveness, and credit policies. Assess inventory management including stock turn, obsolescence, and ordering efficiency. Evaluate accounts payable including payment terms, early payment discounts, and supplier relationship impacts. Calculate current working capital metrics and benchmark against industry standards. Develop action plan to reduce cash cycle by [TARGET] days including specific initiatives, owners, and timelines. Model cash release from working capital improvements and investment opportunities.', 8
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Capital Raising Strategy', 'Develop capital raising strategy for [COMPANY_NAME] seeking [AMOUNT] for [PURPOSE]. Analyse current capital structure and optimal debt-to-equity mix. Evaluate funding options including bank debt, private equity, venture capital, mezzanine finance, or public markets. Prepare detailed information memorandum including investment highlights, financial projections, use of proceeds, and exit opportunities for investors. Develop valuation analysis using multiple methodologies. Create target investor list and engagement strategy. Prepare management presentation materials and Q&A preparation. Include negotiation strategy, term sheet analysis, and deal structure recommendations. Address corporate governance and reporting requirements for each option.', 9
FROM prompt_packs WHERE name = 'CFO Financial Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Financial Risk Management Framework', 'Develop comprehensive financial risk management framework for [COMPANY_NAME] covering all material financial risks. Assess foreign exchange risk from international operations and develop hedging strategy using forwards, options, or natural hedges. Analyse interest rate risk on debt portfolio and evaluate fixing versus floating decisions. Review commodity price exposure and hedging mechanisms. Evaluate credit risk from customer concentration and establish credit insurance or limits. Assess liquidity risk and maintain adequate facility headroom. Review insurance coverages for material risks. Establish risk appetite statements, monitoring metrics, and governance framework. Include compliance with AASB requirements for hedge accounting and derivative disclosures.', 10
FROM prompt_packs WHERE name = 'CFO Financial Leadership';