-- CEO Pack - All 10 prompts
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Strategic Planning Framework', 'Develop a comprehensive 3-5 year strategic plan for [COMPANY_NAME] defining vision, mission, and strategic priorities. Conduct thorough environmental scan including market trends, competitive landscape, regulatory changes, and technological disruptions. Perform SWOT analysis identifying organisational strengths, weaknesses, opportunities, and threats. Define specific strategic objectives with measurable KPIs across growth, profitability, innovation, and people dimensions. Develop strategic initiatives with owners, resources required, timelines, and interdependencies. Create balanced scorecard linking strategy to operations. Include scenario planning for different market conditions and risk mitigation strategies. Address organisational capabilities required and cultural change needed.', 1
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Executive Leadership Team Development', 'Assess and develop the executive leadership team for [COMPANY_NAME] to build high-performing capability. Evaluate current team composition, skills, experience, and gaps relative to strategic requirements. Conduct 360-degree feedback for each executive. Identify succession risks and development needs. Design leadership development program including executive coaching, stretch assignments, and external programs. Address team dynamics, collaboration effectiveness, and decision-making processes. Develop individual development plans with specific goals and accountability. Plan strategic hire requirements including position specifications and search strategy. Implement performance management framework with clear expectations and regular reviews. Foster culture of continuous learning and innovation.', 2
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Stakeholder Engagement Strategy', 'Create comprehensive stakeholder engagement strategy for [COMPANY_NAME] covering investors, board, customers, employees, suppliers, regulators, and community. Map all stakeholder groups, assess their interests and influence, and develop tailored engagement approaches. Design communication plan including frequency, channels, and key messages for each group. Establish feedback mechanisms and issue management protocols. Develop CEO communication calendar including investor presentations, customer forums, town halls, and industry events. Create crisis communication framework with rapid response capability. Include reputation monitoring, brand positioning, and thought leadership strategy. Address corporate social responsibility initiatives and ESG reporting requirements.', 3
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Organisational Culture Transformation', 'Design and implement organisational culture transformation program for [COMPANY_NAME] shifting from current state to desired culture aligned with strategic objectives. Define target culture including values, behaviours, and mindsets required for success. Assess current culture through surveys, focus groups, and observation. Identify culture gaps and root causes. Develop transformation roadmap with specific initiatives including leadership modelling, communication campaigns, recognition programs, and policy changes. Address structural barriers and enablers. Redesign onboarding, performance management, and reward systems to reinforce desired culture. Create culture champions network and feedback mechanisms. Include measurement approach tracking cultural indicators and business impact.', 4
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Board Relationship Management', 'Develop framework for effective board relationship and governance for [COMPANY_NAME]. Define clear roles and responsibilities between board and management. Design annual board calendar including strategy sessions, budget approval, risk reviews, and succession planning. Prepare comprehensive board papers with executive summaries, clear recommendations, and supporting data. Establish proactive communication protocols keeping directors informed between meetings. Create individual director engagement plan building relationships and understanding their expertise. Address board composition, skills matrix, and renewal planning. Implement board evaluation process and continuous improvement. Include crisis escalation protocols and procedures for handling difficult board dynamics. Ensure compliance with all governance obligations and best practice standards.', 5
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Innovation and Digital Transformation', 'Lead digital transformation initiative for [COMPANY_NAME] leveraging technology to drive competitive advantage and operational excellence. Assess current digital maturity across customer experience, operations, and business model. Identify emerging technologies applicable to the industry including AI, automation, data analytics, and cloud platforms. Develop digital strategy with clear use cases and business value. Prioritise initiatives based on impact and feasibility. Design operating model for digital including agile ways of working and cross-functional teams. Address capability gaps through hiring, training, and partnerships. Allocate investment and establish governance for digital portfolio. Create innovation culture encouraging experimentation and calculated risk-taking. Include change management approach and stakeholder engagement.', 6
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'M&A Strategy and Execution', 'Develop mergers and acquisitions strategy for [COMPANY_NAME] to accelerate growth and build competitive position. Define strategic rationale for M&A including market expansion, capability acquisition, or consolidation. Establish target criteria including size, geography, business model, and cultural fit. Build target list and prioritisation framework. Design approach strategy including friendly approach versus competitive process. Prepare investment thesis and valuation framework. Establish due diligence process and integration planning methodology. Define governance including board approval thresholds and decision rights. Build integration playbook covering first 100 days, synergy realisation, and culture integration. Address financing strategy and optimal capital structure post-acquisition. Include lessons learned from previous transactions.', 7
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Crisis Management and Business Continuity', 'Establish comprehensive crisis management and business continuity framework for [COMPANY_NAME] ensuring resilience against major disruptions. Identify potential crisis scenarios including natural disasters, cyber attacks, product failures, financial distress, and reputational issues. Develop crisis response protocols including crisis team composition, escalation procedures, and decision-making authority. Create communication templates for internal and external stakeholders. Establish business continuity plans for critical functions including alternative work arrangements, system backups, and supply chain redundancy. Conduct crisis simulations and tabletop exercises. Define recovery time objectives and resource requirements. Include insurance review, legal considerations, and regulatory notification obligations. Maintain crisis management manual with regular updates.', 8
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Performance Management System', 'Design enterprise-wide performance management system for [COMPANY_NAME] cascading strategy to individual objectives and driving accountability. Develop OKR (Objectives and Key Results) framework linking company objectives to team and individual goals. Create balanced scorecard with financial and non-financial metrics. Establish quarterly business review process evaluating performance, identifying issues, and allocating resources. Design continuous feedback culture replacing annual reviews. Implement performance differentiation with clear consequences for high and low performers. Link performance to compensation through variable pay programs. Create performance development approach including coaching, stretch assignments, and learning opportunities. Address poor performance with clear improvement plans and exit protocols. Include technology platform for transparency and real-time tracking.', 9
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Succession Planning for Critical Roles', 'Develop comprehensive succession planning program for [COMPANY_NAME] ensuring continuity of leadership and critical capabilities. Identify critical roles including executive positions and key technical experts. Assess succession readiness with ready now, ready in 1-2 years, and ready in 3+ years candidates. Evaluate internal talent including potential ratings and development needs. Identify succession gaps requiring external hiring. Design development programs accelerating high-potential leaders including rotational assignments, mentoring, and executive education. Create emergency succession protocols for unexpected departures. Establish talent review process with board involvement for executive positions. Include retention strategies for key talent and knowledge transfer protocols. Document succession plans with regular updates and scenario testing. Address diversity and inclusion objectives in succession planning.', 10
FROM prompt_packs WHERE name = 'CEO Strategic Leadership';