-- Legal Practice Management prompts
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Client Intake Procedure', 'Establish a comprehensive client intake procedure for [legal practice area]. Develop initial enquiry capture system recording potential client contact details, matter type, urgency, referral source, and conflict check requirements. Create initial consultation checklist covering client identification verification (100 points check, proof of identity), client engagement letter explanation, costs disclosure requirements compliant with legal profession regulations, retainer agreement execution, source of funds verification for anti-money laundering compliance, conflict of interest screening across all current and past matters, file opening procedures with matter number allocation, trust account requirements assessment, cost agreement preparation (fixed fee, time-based, conditional), scope of work definition and limitation documentation, client expectations management and timeline communication, file document checklist, electronic file setup in practice management system, task allocation and workflow initiation, initial strategy discussion and advice provision, and follow-up action items. Include risk assessment for difficult clients, limited scope retainer considerations, pro bono eligibility assessment, and referral out procedures if matter outside expertise. Create templates for all intake documents, scripts for difficult conversations about costs, and training materials for reception staff on professional intake conduct.', 1
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Matter Management Workflow', 'Design an end-to-end matter management workflow for [legal practice area - conveyancing, litigation, family law, commercial, etc.]. Create matter lifecycle stages from instruction through completion with defined deliverables and review points, establish task templates for each matter type with standard activities and timeframes, develop document automation for routine correspondence and forms, create critical date tracking system for limitation periods, court dates, settlement deadlines, and compliance requirements, establish file note standards requiring documentation of all client interactions and advice given, develop matter budgeting and cost tracking procedures with variance monitoring, create progress reporting requirements and client update frequency, establish supervisor review points and quality assurance checkpoints, develop risk management protocols for high-risk matters, create matter status classification (active, on hold, completed, archived), establish file closing procedures with final reporting and archival requirements (7+ year retention), develop statistical reporting for matter types, completion times, and profitability, create matter handover procedures for staff changes, establish precedent and template creation from successful matters, and develop client satisfaction assessment at matter conclusion. Include workflow visualisation diagrams, responsibility matrices, and integration with practice management software. Ensure compliance with professional indemnity insurance requirements and law society practice standards.', 2
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Legal Research Methodology', 'Develop a systematic legal research methodology for [legal issue or practice area]. Create research plan identifying key legal questions, relevant jurisdiction, applicable legislation, and case law search parameters. Establish primary source research using authorised legislation databases (federal and state), develop case law research methodology using catchwords, citations, and court hierarchy understanding, create secondary source evaluation including textbooks, journals, practice manuals, and commentary, establish precedent analysis techniques examining binding vs persuasive authority, develop statutory interpretation principles application, create legislative history research for parliamentary intent, establish international and comparative law research when relevant, develop research verification through multiple sources, create research note-taking system with full citations and relevance ratings, establish currency checking for recent amendments and overturned decisions, develop research summary preparation with clear conclusions and confidence levels, create research memorandum template for file documentation, establish research time budgeting and proportionality to matter value, develop research database and precedent library for practice efficiency, and create quality assurance review of research conclusions. Include training on legal research databases (AustLII, LexisNexis, Westlaw, CCH), Boolean search technique optimisation, citator use for case and legislative validity, and AI-assisted research tool integration with appropriate verification protocols.', 3
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Document Drafting Templates', 'Create a comprehensive library of legal document templates for [practice area]. Develop contract templates including appropriate recitals, definitions clause, operative provisions, representations and warranties, conditions precedent/subsequent, indemnities, dispute resolution clauses, governing law and jurisdiction, execution clauses, and schedules. Create pleading templates for different court levels and matter types with proper formatting, establish letter templates for client advice, opposing party correspondence, and third-party communications, develop court application templates with required affidavit structures, create settlement deed templates, develop power of attorney and authorisation forms, establish statutory declaration and affidavit templates compliant with Evidence Act requirements, create opinion letter templates with appropriate disclaimers and limitation language, develop disclosure document templates for costs agreements and engagement terms, establish file note templates for attendance notes and telephone file notes, create checklist templates for due diligence and transaction management, and develop amendment and variation deed templates. Include clause library for common provisions (entire agreement, severability, assignment, confidentiality, force majeure), precedent bank searchable by transaction type and jurisdiction, version control and template update procedures, plain language drafting guidelines balanced with legal precision, and accessibility compliance for client-facing documents. Ensure all templates include prompts for matter-specific customisation and review requirements before use.', 4
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Compliance Management System', 'Establish a comprehensive legal practice compliance management system covering all regulatory obligations. Create trust accounting procedures compliant with Legal Profession Uniform Law including controlled money receipt procedures, payment authorisation protocols, monthly reconciliation requirements, statutory deposit requirements, external examiner facilitation, and trust account record retention. Develop professional indemnity insurance compliance including claims reporting requirements, circumstance notifications, annual declaration accuracy, exclusion understanding, and run-off cover maintenance. Create continuing professional development tracking system meeting law society CPD requirements with substantive law, professional skills, and practice management components. Establish client identification and verification procedures meeting AML/CTF obligations, beneficial owner identification, and ongoing customer due diligence. Develop file management standards for confidentiality, data security, privacy law compliance (Australian Privacy Principles), and cybersecurity protocols. Create conflict of interest checking procedures with conflict register maintenance and disclosure protocols. Establish cost disclosure compliance with billing transparency requirements and dispute resolution procedures. Develop professional conduct compliance monitoring for law society rules, solicitor conduct rules, and professional ethical obligations. Create complaint handling procedures, establish regulatory reporting obligations (law society notifications, significant events), develop risk management procedures for high-risk activities, and create compliance calendar with all statutory obligations and due dates. Include training materials, compliance audit checklists, and breach investigation and remediation procedures.', 5
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Billing and Time Recording', 'Design a comprehensive billing and time recording system for [law firm]. Establish time recording standards requiring contemporaneous entry (within 24 hours), develop activity description guidelines that are meaningful to clients, create time entry templates for common activities, establish minimum time unit policies (6-minute units), develop write-off and discount approval procedures, create billing cycle schedules (monthly, milestone-based, completion), establish invoice generation procedures with detailed narrative explanations of work performed, develop costs agreement compliance verification before billing, create disbursement recording and markup procedures, establish trust account to invoice transfer procedures, develop payment terms and methods, create aged debtors monitoring and collection procedures with escalation protocols, establish payment plan negotiation guidelines, develop statute of limitations tracking for fee recovery, create billing dispute resolution procedures, establish write-off authorisation levels and bad debt provisioning, develop fee estimate update procedures when scope changes, create value billing and alternative fee arrangement frameworks, establish profitability analysis by matter type, lawyer, and client, develop billing target setting and performance monitoring, and create integration between time recording and practice management systems. Include training on value capture (recording all billable activities), efficiency improvement without reducing billing (leveraging junior staff and automation), and client communication about costs to prevent bill shock and disputes. Ensure compliance with legal profession uniform law cost disclosure requirements.', 6
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Conflict Checking Protocol', 'Develop a robust conflict checking protocol for all new matters and client engagements. Create conflict check initiation procedures at first client contact before any confidential information disclosure, establish comprehensive database search parameters including all party names, related entities, alternative trading names, directors, and stakeholders, develop conflict identification categories (direct adversity, confidential information conflicts, duty conflicts, independent legal advice situations, related party transactions), create conflict waiver procedures when appropriate with informed consent documentation, establish ethical wall implementation procedures for manageable conflicts, develop conflict register maintenance with regular updates for entity changes and relationship developments, create declined matter recording for future conflict checking, establish related entity identification procedures for corporate groups, develop geographic and practice area specific conflict considerations, create conflict escalation procedures to ethics partner or committee, establish client notification requirements when conflicts identified, develop matter rejection procedures with professional referral when conflicts insurmountable, create periodic conflict audits for existing matters when new relationships emerge, establish conflict checking for lateral hires and mergers bringing existing client relationships, and develop conflicts training for all staff handling client intake. Include examples of common conflict scenarios (family law parties, litigation opponents, transaction counterparties, multiple beneficiaries), conflict resolution decision trees, and documentation requirements for conflict analysis and management. Ensure compliance with solicitor conduct rules regarding conflicts of interest and confidentiality obligations.', 7
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Court Preparation Guide', 'Create a comprehensive court preparation guide for [court type - Magistrates, District, Supreme, Federal Circuit, Family Court]. Develop matter analysis checklist covering strengths and weaknesses assessment, evidence compilation and organisation, witness preparation requirements, and anticipated opposing arguments. Establish court document preparation including originating process verification, supporting affidavits with proper exhibits and annexures, outline of submissions or written arguments, list of authorities with copies, court book preparation compliant with practice directions, and chronology of relevant events. Create procedural compliance checking for filing deadlines, service requirements, fee payment, and hearing date confirmation. Develop courtroom procedure review covering appropriate attire, court etiquette, device usage policies, speaking protocols, objection procedures, and examination techniques. Create witness preparation procedures including explaining court process, evidence rules, cross-examination techniques, document familiarity, and managing stress. Establish backup planning for technology failures, delayed witnesses, and unexpected objections. Develop post-hearing procedures for order drafting, costs applications, enforcement considerations, and appeal rights notification. Create client expectation management including realistic outcome assessment, cost implications, timeline understanding, and emotional preparation. Include court-specific practice directions, judicial preferences research, matter mention strategies, negotiation opportunities before hearing, and settlement authority parameters. Develop courtroom technology setup (video conferencing, electronic bundles), accommodation and travel logistics for regional courts, and supervision requirements for junior practitioners.', 8
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Client Communication Framework', 'Establish a professional client communication framework for all matters. Develop communication style guidelines balancing legal precision with client understanding (avoiding unnecessary jargon, explaining technical terms, using active voice). Create written communication standards for emails and letters including professional formatting, clear subject lines, appropriate salutations, logical structure, action item clarity, and professional signatures. Establish verbal communication protocols for client meetings, telephone advice, and difficult conversations about adverse developments or costs. Develop expectation setting procedures covering realistic timelines, likely outcomes with risk assessment, cost projections, and client responsibilities. Create regular update requirements with minimum contact frequency based on matter status and complexity. Establish bad news delivery protocols with empathy, solution focus, and managing emotional responses. Develop client instruction confirmation procedures with file note requirements and written confirmation for significant decisions. Create accessibility standards for clients with disabilities, language barriers (interpreter use), or communication preferences. Establish response time standards for client enquiries (acknowledging within 24 hours, substantive response within 48 hours). Develop escalation procedures when clients dissatisfied or communication breakdown occurs. Create communication documentation requirements with comprehensive file noting. Establish boundaries for after-hours contact and emergency procedures. Develop client education materials explaining legal processes, terminology, and court systems. Include training scenarios for difficult client communications (angry clients, unrealistic expectations, scope creep, non-payment), cultural competency considerations, and trauma-informed communication for sensitive matters (family law, criminal law, personal injury).', 9
FROM prompt_packs WHERE name = 'Legal Practice Management';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Case Strategy Development', 'Design a comprehensive case strategy development framework for [matter type]. Create initial matter assessment examining legal merits, factual strengths and weaknesses, evidence availability, witness credibility, and likelihood of success. Develop client objectives clarification including primary goals, acceptable compromise positions, risk tolerance, and budget constraints. Establish legal research requirements identifying relevant laws, precedents, and alternative arguments. Create evidence gathering strategy including document discovery, witness statements, expert reports, and demonstrative evidence. Develop procedural planning with court timeline understanding, interlocutory applications strategy, and case management compliance. Establish negotiation strategy including settlement position development, BATNA identification, and tactical concessions planning. Create risk assessment covering adverse costs exposure, reputational considerations, time and resource investment, and precedent implications. Develop alternative dispute resolution evaluation for mediation, arbitration, or expert determination suitability. Establish opposing party analysis including likely strategy, settlement motivation, and financial capacity. Create contingency planning for unfavourable evidentiary rulings, witness unavailability, or case law developments. Develop costs-benefit analysis weighing likely recovery against legal costs and opportunity costs. Create case theory narrative that synthesises facts, law, and client objectives into compelling advocacy. Establish regular strategy review points adapting to new information and changing circumstances. Include strategy documentation for file records and supervisor review, client consultation on strategic decisions, ethical considerations ensuring strategy within professional conduct rules, and learning capture from strategy effectiveness for continuous improvement.', 10
FROM prompt_packs WHERE name = 'Legal Practice Management';