-- Office Administration Pack - All 10 prompts
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Office Supplies Inventory Management', 'Develop a comprehensive office supplies inventory management system for [COMPANY_NAME] covering ordering, storage, and usage tracking. Create master inventory list categorised by type (stationery, printing, kitchen, cleaning). Establish par levels and reorder points based on consumption patterns. Design requisition process with approval workflows. Negotiate supplier contracts for volume discounts and establish preferred vendor list. Implement inventory tracking system with issue logs. Conduct monthly stocktakes and reconciliation. Calculate cost per employee and identify savings opportunities. Include sustainable procurement options and waste reduction strategies. Create budget forecast and variance reporting. Address special order procedures and urgent requirement protocols.', 1
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Reception and Visitor Management', 'Establish professional reception and visitor management procedures for [COMPANY_NAME] ensuring excellent first impressions and security compliance. Design visitor check-in process including sign-in requirements, identification verification, and badge issuance. Create visitor log with privacy compliance. Develop standard greetings and telephone answering protocols. Prepare building orientation information including amenities, evacuation procedures, and WiFi access. Establish host notification systems and visitor escorting policies. Design reception area to be welcoming with appropriate seating, refreshments, and reading materials. Include procedures for handling deliveries, couriers, and unexpected visitors. Address accessibility requirements and multilingual capabilities. Implement feedback mechanism to continuously improve visitor experience.', 2
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Meeting Room Booking System', 'Implement efficient meeting room booking and management system for [COMPANY_NAME] maximising utilisation and minimising conflicts. Establish booking platform with real-time availability, capacity information, and equipment listings. Create booking policies including advance notice, duration limits, and cancellation requirements. Design room setup configurations (boardroom, presentation, workshop) with corresponding equipment. Develop room turnover procedures including cleaning between bookings and equipment reset. Implement no-show policy and utilisation reporting. Provide catering ordering integration and dietary requirements management. Include videoconference testing protocols and technical support contacts. Create room naming convention and wayfinding signage. Address hybrid meeting requirements with appropriate technology in each space.', 3
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Document Filing and Records Management', 'Design comprehensive filing and records management system for [COMPANY_NAME] ensuring efficient retrieval and compliance with retention requirements. Create logical filing structure with clear naming conventions and version control. Establish physical filing system with labels, colour coding, and location mapping. Develop digital filing guidelines including folder structures, file naming, and cloud storage organisation. Define document retention schedule based on legal requirements and business needs. Implement secure disposal procedures for confidential materials. Create archiving process for inactive records with index for future retrieval. Address backup procedures and disaster recovery. Include training materials for staff on filing protocols. Conduct annual records audit and clean-up process.', 4
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Office Facilities Maintenance', 'Manage office facilities maintenance program for [COMPANY_NAME] ensuring safe, functional, and pleasant work environment. Create preventative maintenance schedule for HVAC, electrical, plumbing, and equipment. Establish relationships with reliable contractors and maintenance providers. Implement work order system for reactive maintenance with priority classifications. Conduct regular workplace inspections identifying hazards and maintenance needs. Manage cleaning contracts with quality monitoring and feedback mechanisms. Coordinate building access, security systems, and alarm management. Plan office refurbishments and space reconfigurations. Address sustainability initiatives including energy efficiency, waste management, and recycling programs. Maintain asset register and warranty documentation. Include emergency procedures for facilities failures.', 5
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Mail and Package Distribution', 'Establish efficient mail and package handling system for [COMPANY_NAME] covering incoming and outgoing items. Design receiving process including logging, scanning, and notification to recipients. Create internal distribution runs with regular schedule. Implement tracking system for registered and urgent items. Establish courier booking procedures with account management and cost allocation. Develop outgoing mail process including postage, packaging standards, and collection times. Address confidential mail handling and security protocols. Create procedures for refused deliveries and undeliverable items. Implement cost control measures including postal alternatives and bulk discounts. Include international shipping procedures with customs documentation. Establish lost item protocols and investigation procedures.', 6
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Office Events and Functions', 'Plan and coordinate office events and functions for [COMPANY_NAME] including staff celebrations, client functions, and corporate events. Develop event planning checklist covering venue selection, catering, entertainment, and logistics. Create budget template with cost tracking. Design invitation process with RSVP management and attendee communications. Coordinate setup including decorations, AV equipment, and seating arrangements. Manage dietary requirements and accessibility needs. Establish alcohol service guidelines and responsible service protocols. Create event run sheet with timing and responsibilities. Coordinate photography and post-event communications. Include evaluation process gathering feedback for continuous improvement. Address WHS considerations and emergency procedures. Develop relationships with preferred suppliers and venues.', 7
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'New Employee Workspace Setup', 'Coordinate comprehensive workspace setup for new employee [NAME] starting [DATE] in role of [POSITION]. Arrange desk allocation considering team proximity and collaboration needs. Order and configure computer equipment including laptop, monitor, keyboard, mouse, and docking station. Set up phone extension and voicemail. Provide office supplies starter pack and stationery. Arrange building access card, parking permit, and security clearances. Coordinate IT account creation and system access. Prepare welcome pack including organisational chart, phone list, and company information. Book workstation for ergonomic setup and adjust chair. Arrange name plate, business cards, and email signature. Include first day orientation covering amenities, emergency procedures, and office protocols. Ensure all equipment functional before start date.', 8
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Petty Cash Management', 'Administer petty cash system for [COMPANY_NAME] ensuring appropriate controls and accountability. Establish float amount and custody arrangements with secure storage. Define approved expenditure categories and individual transaction limits. Create requisition and approval process with supporting receipt requirements. Implement voucher system with sequential numbering. Conduct regular reconciliations matching receipts to disbursements. Establish reimbursement process to restore float to set amount. Maintain detailed ledger with coding to expense categories. Create monthly reporting to finance team. Address GST treatment and tax invoice requirements. Implement spot checks and annual audit procedures. Define procedures for handling float shortages or overages. Include staff training on petty cash policies and authorisation levels.', 9
FROM prompt_packs WHERE name = 'Office Administration';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Travel and Accommodation Booking', 'Manage corporate travel and accommodation bookings for [COMPANY_NAME] staff ensuring cost-effectiveness and policy compliance. Establish relationships with preferred travel providers and negotiate corporate rates. Create travel booking procedures including advance notice requirements and approval workflows. Design travel policy covering class of travel, accommodation standards, and expense limits. Implement booking platform with policy controls and traveller profiles. Provide travel itinerary format including confirmations, meeting details, and emergency contacts. Address duty of care obligations including travel insurance, risk assessments, and emergency support. Coordinate group travel logistics for conferences and training. Implement expense reconciliation linking bookings to credit card statements. Create travel metrics reporting including cost per trip and policy compliance. Include sustainable travel options and carbon offset programs.', 10
FROM prompt_packs WHERE name = 'Office Administration';