-- Pack 29: Serverless Architecture (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Serverless Application Design', 'Design serverless applications using functions-as-a-service. Include function design patterns, event-driven architecture, state management, and orchestration. Implement API Gateway integration, authentication, authorization, and error handling. Address cold start optimization, concurrency limits, and timeout management. Design observability, logging, and distributed tracing. Provide architecture patterns, best practises, and cost optimization using serverless design principles and Australian cloud architecture standards.', 0 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'AWS Lambda Best Practises', 'Implement AWS Lambda functions following best practises. Include function configuration, runtime selection, layer management, and dependency optimization. Design environment variables, secrets management, VPC integration, and IAM permissions. Address package size optimization, memory tuning, and execution optimization. Implement monitoring with CloudWatch, X-Ray tracing, and custom metrics. Provide Lambda patterns, deployment strategies, and troubleshooting guides using AWS serverless best practises and Australian cloud standards.', 1 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Serverless Data Processing', 'Build serverless data processing pipelines. Include event-driven data ingestion, transformation functions, batch processing, and real-time streaming. Design S3 event triggers, Kinesis processing, DynamoDB streams, and EventBridge integration. Address parallel processing, error handling, dead letter queues, and retry strategies. Implement data validation, idempotency, and exactly-once processing. Provide pipeline architectures, cost optimization, and monitoring strategies using serverless data patterns and Australian data processing standards.', 2 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Serverless API Development', 'Develop RESTful and GraphQL APIs using serverless. Include API Gateway configuration, Lambda integration, request validation, and response transformation. Design API versioning, rate limiting, caching, and CORS handling. Address authentication with Cognito, custom authorizers, and API keys. Implement API documentation, monitoring, and cost attribution. Provide API design patterns, security hardening, and performance optimization using serverless API best practises and Australian API standards.', 3 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Serverless Security Hardening', 'Implement security for serverless applications. Include function-level IAM policies, least privilege principles, secrets management, and input validation. Design network security with VPC, security groups, and private endpoints. Address dependency scanning, vulnerability management, and compliance. Implement logging, monitoring, and security incident response. Provide security checklists, threat modelling, and audit procedures using serverless security frameworks and Australian cybersecurity standards.', 4 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Serverless State Management', 'Manage state in serverless applications. Include stateless function design, external state storage with DynamoDB, caching with ElastiCache, and session management. Design workflow orchestration with Step Functions, long-running processes, and distributed transactions. Address consistency models, data access patterns, and performance optimization. Implement state machine design, error recovery, and monitoring. Provide state management patterns, architecture decisions, and scaling strategies using serverless state patterns and Australian application design standards.', 5 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Serverless Cost Optimization', 'Optimise costs for serverless deployments. Include function sizing, execution time optimization, memory allocation, and request reduction. Design architecture for cost efficiency, reserved capacity usage, and tiered pricing leverage. Address cold start reduction impact on costs, unused resource cleanup, and cost monitoring. Implement budget alerts, cost allocation tags, and showback/chargeback. Provide cost optimization strategies, monitoring dashboards, and governance policies using FinOps principles and Australian cloud cost management standards.', 6 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Serverless CI/CD Pipeline', 'Build CI/CD pipelines for serverless applications. Include infrastructure as code with SAM or Serverless Framework, automated testing, canary deployments, and blue-green deployments. Design environment management, promotion workflows, and rollback procedures. Address deployment validation, integration testing, and performance testing. Implement deployment monitoring, automated rollback triggers, and approval gates. Provide pipeline templates, deployment strategies, and operational procedures using serverless DevOps best practises and Australian deployment standards.', 7 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Event-Driven Serverless Patterns', 'Implement event-driven patterns in serverless architecture. Include event sourcing, CQRS, saga patterns, and event choreography. Design EventBridge rules, SNS/SQS integration, and event filtering. Address event schema evolution, dead letter handling, and event replay. Implement distributed tracing across events, event auditing, and monitoring. Provide event-driven architecture patterns, implementation guides, and troubleshooting strategies using reactive architecture principles and Australian event-driven design standards.', 8 FROM prompt_packs WHERE name = 'Serverless Architecture'
UNION ALL
SELECT id, 'Serverless Monitoring & Observability', 'Implement comprehensive observability for serverless applications. Include CloudWatch Logs aggregation, X-Ray distributed tracing, custom metrics, and alerts. Design log correlation, error tracking, performance monitoring, and cost tracking. Address cold start monitoring, throttling detection, and concurrency tracking. Implement dashboards for operational visibility, anomaly detection, and SLA monitoring. Provide observability strategy, tooling recommendations, and operational runbooks using observability best practises and Australian monitoring standards.', 9 FROM prompt_packs WHERE name = 'Serverless Architecture';