-- Complete Packs 14-50 (all with 10 detailed prompts each, Australian spelling throughout)
-- Pack 14: Cybersecurity
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Application Security Assessment', 'Conduct comprehensive security assessment. Include: 1) OWASP Top 10 vulnerability testing, 2) Authentication and session management review, 3) Input validation and sanitisation, 4) SQL injection prevention, 5) XSS and CSRF protection, 6) Security headers implementation, 7) API security testing, 8) Penetration testing methodology. Provide security audit checklist using Australian spelling.', 1
FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Penetration Testing & Ethical Hacking', 'Perform penetration testing. Include: 1) Reconnaissance and information gathering, 2) Vulnerability scanning, 3) Exploitation techniques, 4) Privilege escalation, 5) Post-exploitation, 6) Reporting findings, 7) Remediation recommendations, 8) Responsible disclosure. Provide testing methodology using Australian spelling.', 2 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Security Incident Response', 'Design incident response plan. Include: 1) Detection and analysis, 2) Containment strategies, 3) Eradication procedures, 4) Recovery steps, 5) Post-incident analysis, 6) Communication protocols, 7) Evidence preservation, 8) Lessons learnt documentation. Provide incident playbooks using Australian spelling.', 3 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Network Security Architecture', 'Design secure network architecture. Include: 1) Firewall configuration, 2) IDS/IPS implementation, 3) Network segmentation, 4) VPN setup, 5) Zero-trust architecture, 6) DDoS protection, 7) Network monitoring, 8) Secure remote access. Provide network diagrams using Australian spelling.', 4 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Identity & Access Management', 'Implement IAM solutions. Include: 1) Authentication mechanisms, 2) Multi-factor authentication, 3) Single sign-on integration, 4) Role-based access control, 5) Privileged access management, 6) Password policies, 7) Identity federation, 8) Access auditing. Provide IAM implementation using Australian spelling.', 5 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Data Encryption & Privacy', 'Implement data protection. Include: 1) Encryption at rest, 2) Encryption in transit, 3) Key management, 4) Data classification, 5) Privacy by design, 6) GDPR compliance, 7) Data retention policies, 8) Secure data disposal. Provide encryption implementations using Australian spelling.', 6 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Security Monitoring & SIEM', 'Implement security monitoring. Include: 1) SIEM setup, 2) Log aggregation, 3) Alert correlation, 4) Threat intelligence integration, 5) Anomaly detection, 6) Security dashboards, 7) Incident escalation, 8) Compliance reporting. Provide SIEM configuration using Australian spelling.', 7 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Cloud Security Best Practises', 'Secure cloud infrastructure. Include: 1) IAM policies, 2) Security groups configuration, 3) Encryption implementation, 4) Compliance frameworks, 5) Vulnerability management, 6) Container security, 7) Serverless security, 8) Cloud security posture management. Provide cloud security configs using Australian spelling.', 8 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Security Awareness Training', 'Design security training programme. Include: 1) Phishing awareness, 2) Password security, 3) Social engineering defence, 4) Data handling procedures, 5) Incident reporting, 6) Compliance requirements, 7) Mobile device security, 8) Security culture building. Provide training materials using Australian spelling.', 9 FROM prompt_packs WHERE name = 'Cybersecurity'
UNION ALL SELECT id, 'Compliance & Governance', 'Implement security compliance. Include: 1) ISO 27001 framework, 2) SOC 2 requirements, 3) PCI DSS compliance, 4) GDPR implementation, 5) Risk assessment, 6) Policy documentation, 7) Audit preparation, 8) Continuous monitoring. Provide compliance checklists using Australian spelling.', 10 FROM prompt_packs WHERE name = 'Cybersecurity';

-- Pack 15: Documentation Writing (complete with 10 prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Technical Documentation Standards', 'Create technical documentation. Include: 1) Documentation structure, 2) Writing style guide, 3) Code examples format, 4) Diagram standards, 5) Version control, 6) Review process, 7) Accessibility, 8) Maintenance procedures. Provide documentation templates using Australian spelling.', 1 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'API Documentation', 'Write comprehensive API docs. Include: 1) Endpoint descriptions, 2) Request/response examples, 3) Authentication guide, 4) Error codes, 5) Rate limiting, 6) SDKs usage, 7) Tutorials, 8) Interactive testing. Provide API doc examples using Australian spelling.', 2 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'User Guides & Tutorials', 'Create user documentation. Include: 1) Getting started guide, 2) Feature tutorials, 3) Troubleshooting section, 4) FAQs, 5) Screenshots and videos, 6) Best practises, 7) Use cases, 8) Glossary. Provide user guide structure using Australian spelling.', 3 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'README & Project Documentation', 'Write excellent README files. Include: 1) Project description, 2) Installation instructions, 3) Usage examples, 4) Configuration options, 5) Contributing guidelines, 6) Licence information, 7) Credits, 8) Badges and status. Provide README templates using Australian spelling.', 4 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'Code Comments & Inline Documentation', 'Write effective code comments. Include: 1) When to comment, 2) Documentation comments, 3) Function descriptions, 4) Complex logic explanation, 5) TODO and FIXME usage, 6) Deprecation notices, 7) Examples in comments, 8) Maintenance of comments. Provide commenting guidelines using Australian spelling.', 5 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'Architecture Decision Records', 'Document architectural decisions. Include: 1) ADR template, 2) Context description, 3) Decision rationale, 4) Alternatives considered, 5) Consequences, 6) Status tracking, 7) Linking decisions, 8) Review process. Provide ADR examples using Australian spelling.', 6 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'Release Notes & Changelogs', 'Write release documentation. Include: 1) Version numbering, 2) Feature descriptions, 3) Bug fixes, 4) Breaking changes, 5) Migration guides, 6) Deprecation notices, 7) Known issues, 8) Contributors. Provide changelog format using Australian spelling.', 7 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'Runbooks & Operational Guides', 'Create operational documentation. Include: 1) Deployment procedures, 2) Monitoring setup, 3) Troubleshooting steps, 4) Incident response, 5) Rollback procedures, 6) Configuration management, 7) Disaster recovery, 8) Contact information. Provide runbook templates using Australian spelling.', 8 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'Onboarding Documentation', 'Design onboarding docs. Include: 1) Environment setup, 2) Codebase overview, 3) Development workflow, 4) Testing procedures, 5) Deployment process, 6) Team contacts, 7) Learning resources, 8) First tasks guide. Provide onboarding checklist using Australian spelling.', 9 FROM prompt_packs WHERE name = 'Documentation Writing'
UNION ALL SELECT id, 'Documentation Tools & Automation', 'Implement documentation automation. Include: 1) Documentation generators, 2) API doc automation, 3) Diagram generation, 4) Version management, 5) Search implementation, 6) Hosting solutions, 7) Update workflows, 8) Analytics tracking. Provide tooling setup using Australian spelling.', 10 FROM prompt_packs WHERE name = 'Documentation Writing';