-- Pack 25: Digital Transformation (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Digital Strategy Roadmap', 'Develop a comprehensive digital transformation strategy and roadmap. Include current state assessment, future state vision, capability gap analysis, technology selection, change management approach, and implementation timeline. Design transformation pillars (customer experience, operations, business model, culture), KPIs for success, and governance structure. Address stakeholder alignment, budget planning, risk mitigation, and quick wins. Provide roadmap templates, business case development, and progress tracking using digital transformation frameworks and Australian business strategy standards.', 0 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Legacy System Modernisation', 'Plan legacy system modernisation strategy balancing risk and innovation. Include system inventory, technical debt assessment, modernisation approaches (rehost, replatform, refactor, rebuild, replace), and prioritisation. Design phased migration, data migration strategy, integration patterns, and parallel running. Address business continuity, user training, and rollback procedures. Provide decision frameworks, ROI analysis, and vendor evaluation criteria using modernisation best practises and Australian technology refresh standards.', 1 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Change Management Framework', 'Implement change management framework for digital transformation. Include stakeholder analysis, communication strategy, training programmes, resistance management, and adoption metrics. Design change champions network, feedback mechanisms, and continuous engagement. Address cultural transformation, leadership alignment, and behaviour change. Provide change management plans, communication templates, and success metrics using organisational change management methodologies and Australian workplace transformation practises.', 2 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Cloud Migration Strategy', 'Design cloud migration strategy for digital transformation. Include cloud readiness assessment, migration patterns (lift-and-shift, re-platform, re-architect), workload prioritisation, and landing zone design. Implement migration waves, testing strategy, cutover planning, and rollback procedures. Address cost optimisation, security hardening, and compliance. Provide migration playbooks, architecture patterns, and cloud governance framework using cloud adoption frameworks and Australian cloud security standards.', 3 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Digital Customer Experience', 'Transform customer experience through digital channels. Include customer journey mapping, omnichannel strategy, personalisation engine, and self-service capabilities. Design mobile-first experiences, conversational interfaces, and seamless integrations. Address accessibility, performance, and customer feedback loops. Implement analytics for experience measurement, A/B testing, and continuous optimisation. Provide CX metrics, design systems, and customer-centric culture building using experience design methodologies and Australian customer service standards.', 4 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Agile Transformation', 'Transform organisation to agile ways of working. Include agile maturity assessment, framework selection (Scrum, Kanban, SAFe), team structure redesign, and skill development. Design sprint cadences, ceremonies, and artifacts. Address scaling agile across organisation, distributed teams, and agile culture. Implement metrics for agile health, continuous improvement mechanisms, and coaching programmes. Provide transformation roadmap, training materials, and success metrics using agile scaling frameworks and Australian agile practises.', 5 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Data-Driven Organisation', 'Transform organisation into data-driven culture. Include data strategy, data governance, data literacy programmes, and analytics capabilities. Design self-service analytics platforms, data democratisation, and insight activation processes. Address data quality, privacy compliance, and ethical AI. Implement metrics culture, experimentation mindset, and decision frameworks. Provide data maturity assessment, capability building programmes, and governance structures using data strategy frameworks and Australian data governance standards.', 6 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Digital Product Management', 'Establish digital product management capabilities. Include product vision and strategy, roadmap planning, discovery and validation, and delivery excellence. Design product operating model, cross-functional collaboration, and stakeholder management. Address product metrics, experimentation, and continuous discovery. Implement product ops, portfolio management, and product-led growth. Provide product management frameworks, templates, and capability development using modern product management practises and Australian product leadership standards.', 7 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Innovation Culture Building', 'Build innovation culture within organisation. Include innovation strategy, ideation processes, experimentation frameworks, and failure tolerance. Design innovation labs, hackathons, innovation metrics, and portfolio management. Address intrapreneurship programmes, partnerships with startups, and open innovation. Implement idea management systems, rapid prototyping, and scaling mechanisms. Provide innovation playbooks, assessment tools, and leadership development using innovation management frameworks and Australian entrepreneurship practises.', 8 FROM prompt_packs WHERE name = 'Digital Transformation'
UNION ALL
SELECT id, 'Digital Operating Model', 'Design digital operating model for transformation success. Include organisational structure, roles and responsibilities, ways of working, and governance. Design squad models, platform teams, enabling teams, and centre of excellence. Address budget and funding models, performance management, and career paths. Implement collaboration tools, distributed work enablement, and knowledge sharing. Provide operating model blueprints, transition plans, and maturity models using digital organisation design principles and Australian workplace frameworks.', 9 FROM prompt_packs WHERE name = 'Digital Transformation';

-- Pack 26: Content Management Systems (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Headless CMS Architecture', 'Design headless CMS architecture for omnichannel content delivery. Include CMS selection (Contentful, Strapi, Sanity), content modelling, API design, and content delivery network integration. Implement versioning, workflows, localization, and media management. Address preview environments, webhooks for publishing, and edge caching. Provide migration strategy from traditional CMS, developer experience, and scaling considerations using JAMstack principles and Australian content strategy standards.', 0 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Content Modelling Strategy', 'Create content modelling strategy for flexible content management. Include content types, relationships, taxonomies, metadata schemas, and reusability patterns. Design structured content, component-based approach, and content governance. Address localization requirements, content hierarchies, and versioning. Implement content migration mapping, validation rules, and editorial workflows. Provide modelling documentation, governance policies, and content lifecycle management using information architecture principles and Australian content governance frameworks.', 1 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Editorial Workflow Design', 'Design editorial workflows for content creation and publishing. Include content planning, drafting, review, approval, scheduling, and publishing. Implement role-based permissions, collaborative editing, version control, and change tracking. Address multi-stage approvals, legal reviews, and compliance checks. Provide workflow automation, notification systems, and audit trails. Design workflow templates, escalation procedures, and SLA management using content operations best practises and Australian publishing standards.', 2 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Multi-Site CMS Implementation', 'Implement CMS for managing multiple websites and brands. Include shared content repository, site-specific customisation, template management, and brand governance. Design content sharing and inheritance, URL management, and site switching. Address performance isolation, independent deployment, and centralized reporting. Implement global vs local content strategies, regional overrides, and master brand guidelines. Provide multi-tenancy architecture, governance frameworks, and operational procedures using enterprise CMS patterns and Australian multi-brand management standards.', 3 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Content Localization & Translation', 'Implement content localization and translation management. Include locale configuration, translation workflows, translation memory integration, and linguistic quality assurance. Design fallback strategies, regional content variations, and cultural adaptations. Address RTL language support, date/time formatting, and currency handling. Implement machine translation integration, translator collaboration tools, and glossary management. Provide localization processes, quality metrics, and cost optimization using internationalization best practises and Australian multilingual content standards.', 4 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'CMS Performance Optimization', 'Optimise CMS performance for editorial and end-user experience. Include database query optimization, caching strategies, asset optimization, and CDN configuration. Design lazy loading, incremental static regeneration, and edge rendering. Address large content libraries, media optimization, and search performance. Implement performance monitoring, bottleneck identification, and continuous optimization. Provide performance budgets, optimization checklists, and scaling strategies using web performance principles and Australian digital experience standards.', 5 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Content Security & Access Control', 'Implement security and access control for CMS. Include role-based access control, content permissions, authentication integration, and audit logging. Design content encryption, secure publishing workflows, and vulnerability management. Address user provisioning, password policies, and session management. Implement content approval gates, sensitive content handling, and compliance requirements. Provide security policies, access review procedures, and incident response using security best practises and Australian information security standards.', 6 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Content Analytics & Insights', 'Implement analytics and insights for content performance. Include page analytics integration, content engagement metrics, conversion tracking, and A/B testing. Design editorial analytics dashboards, content ROI measurement, and audience insights. Address attribution modelling, content journey analysis, and performance benchmarking. Implement recommendations for content optimization, trending content alerts, and predictive analytics. Provide analytics frameworks, reporting templates, and data-driven content strategy using content intelligence methodologies and Australian digital analytics standards.', 7 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Content Migration Planning', 'Plan and execute content migration to new CMS. Include content audit, migration scope definition, content mapping, and data transformation. Design migration scripts, validation procedures, and rollback strategies. Address URL preservation, SEO considerations, and content cleanup. Implement phased migration, parallel running, and cutover planning. Provide migration runbooks, testing protocols, and post-migration validation using content migration methodologies and Australian digital transformation standards.', 8 FROM prompt_packs WHERE name = 'Content Management Systems'
UNION ALL
SELECT id, 'Component-Based Content Design', 'Design component-based content architecture for reusability. Include component library, design tokens, content blocks, and layout systems. Implement component composition, nested structures, and dynamic rendering. Address responsive components, accessibility, and performance. Design component documentation, usage guidelines, and governance. Provide component versioning, deprecation strategy, and migration paths using atomic design principles and Australian content architecture standards.', 9 FROM prompt_packs WHERE name = 'Content Management Systems';