-- Pack 24: Incident Management (10 detailed prompts)
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Incident Response Framework', 'Establish an incident response framework aligned with ITIL or similar standards. Include incident classification (severity levels, priority matrix), escalation procedures, communication protocols, and resolution tracking. Design incident lifecycle from detection to post-mortem, roles and responsibilities, and tooling requirements. Address major incident management, war room procedures, and stakeholder communication. Provide incident templates, status page management, and continuous improvement processes using Australian incident management frameworks and service management standards.', 0 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'On-Call Rotation Strategy', 'Design an effective on-call rotation strategy for incident response. Include rotation schedules, primary and secondary on-call, handoff procedures, and alerting configuration. Implement escalation policies, alert fatigue reduction, and fair distribution. Address timezone considerations, on-call compensation, and burnout prevention. Provide on-call runbooks, shadowing for new members, and metrics for on-call load. Use site reliability engineering principles and Australian workplace practises for healthy on-call culture.', 1 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Incident Communication Plan', 'Create an incident communication plan for internal and external stakeholders. Include status page updates, incident notifications, stakeholder briefings, and post-incident communications. Design communication templates, notification channels (email, Slack, SMS), and escalation triggers. Address transparency practises, customer communication timing, and regulatory notifications. Provide communication checklists, approval workflows, and message testing using crisis communication principles and Australian service communication standards.', 2 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Post-Mortem Process', 'Implement a blameless post-mortem process for learning from incidents. Include timeline reconstruction, root cause analysis (5 Whys, Fishbone diagram), contributing factors identification, and action item creation. Design post-mortem template, facilitation guidelines, and documentation. Address psychological safety, learning culture, and action item tracking. Provide post-mortem examples, follow-up procedures, and knowledge sharing mechanisms using retrospective facilitation techniques and Australian continuous improvement frameworks.', 3 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Alert Configuration & Tuning', 'Configure and optimise alerting systems to reduce noise and improve response. Include alert definitions based on SLOs, severity classification, alert routing, and de-duplication. Implement alert grouping, intelligent escalation, and context enrichment. Address alert fatigue, false positive reduction, and alert coverage. Provide alert tuning methodology, review cycles, and effectiveness metrics using observability best practises and Australian monitoring standards.', 4 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Incident Metrics & Reporting', 'Establish incident metrics and reporting for continuous improvement. Include MTTR (Mean Time to Resolution), MTTD (Mean Time to Detection), MTTA (Mean Time to Acknowledge), incident frequency, and severity distribution. Design incident dashboards, trend analysis, and executive reporting. Address metric definitions, data collection, and benchmarking. Provide reporting templates, review cadences, and improvement initiatives using service level management principles and Australian performance reporting standards.', 5 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Chaos Engineering Practises', 'Implement chaos engineering to proactively identify system weaknesses. Include chaos experiments design, hypothesis formation, blast radius control, and automated rollback. Design game days, failure injection techniques (latency, errors, resource exhaustion), and steady-state validation. Address safety controls, production testing, and team training. Provide chaos engineering tools (Chaos Monkey, Gremlin), experiment documentation, and learning integration using resilience engineering principles and Australian risk management frameworks.', 6 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Incident Priority Matrix', 'Design an incident priority matrix for consistent incident classification. Include severity levels (Critical, High, Medium, Low), impact assessment (users affected, revenue impact, security implications), and urgency factors. Implement priority assignment guidelines, SLA mapping, and escalation triggers. Address edge case handling, priority re-evaluation, and business context. Provide priority decision trees, training materials, and audit procedures using ITIL service management principles and Australian business impact frameworks.', 7 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Incident Response Automation', 'Automate incident response processes to reduce MTTR. Include auto-remediation for common issues, automated diagnostics, chatbot integrations (ChatOps), and automated notification dispatch. Design automation workflows, safety controls, and audit logging. Address escalation to humans when needed, automation testing, and continuous improvement. Provide automation platform selection (PagerDuty, Opsgenie), runbook automation, and metrics tracking using DevOps automation principles and Australian operational efficiency standards.', 8 FROM prompt_packs WHERE name = 'Incident Management'
UNION ALL
SELECT id, 'Service Level Objectives (SLOs)', 'Define and implement Service Level Objectives for reliability management. Include SLI (Service Level Indicator) selection, SLO target setting based on user expectations, error budgets, and burn rate alerting. Design SLO documentation, stakeholder agreement, and monitoring dashboards. Address SLO violations, error budget policies, and feature velocity trade-offs. Provide SLO examples, review processes, and adjustment procedures using site reliability engineering methodologies and Australian service excellence frameworks.', 9 FROM prompt_packs WHERE name = 'Incident Management';