-- Real Estate Operations prompts
INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Property Listing Optimisation', 'Create a comprehensive property listing for a [property type] located at [address] with [number] bedrooms, [number] bathrooms, and [key features]. Include an attention-grabbing headline that highlights the property''s unique selling propositions, a detailed description emphasising lifestyle benefits and local amenities within [suburb/area], high-impact feature bullet points, comparable recent sales data for the area, suggested price range based on current market conditions, ideal buyer persona, recommended staging improvements, professional photography shot list, social media marketing angles, and open home scheduling strategy. Ensure all descriptions comply with fair trading regulations and avoid discriminatory language while maximising emotional appeal to potential buyers.', 1
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Market Analysis Report', 'Generate a comprehensive market analysis report for [suburb/region] covering the past [timeframe]. Include median house and unit prices with quarterly trends, days on market analysis, auction clearance rates, rental yield calculations, supply and demand indicators, demographic trends affecting property values, infrastructure developments and their impact, school zone analysis, comparative suburb analysis, interest rate impact assessment, seasonal market patterns, investment opportunity identification, buyer activity levels by property type, price growth forecasts for the next 12-24 months, and strategic recommendations for sellers and buyers. Present data using clear visualisations and actionable insights for client decision-making.', 2
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Buyer Communication Framework', 'Develop a communication strategy for engaging with [buyer type] interested in [property type] in [location]. Create email templates for initial enquiry response, property information follow-up, inspection scheduling, post-inspection feedback request, offer negotiation, contract progression, and settlement coordination. Include SMS templates for time-sensitive communications, phone call scripts for different buyer scenarios, objection handling responses for common concerns (price, location, condition, settlement terms), competing offer management language, and relationship nurturing content for buyers not yet ready to purchase. Ensure all communications maintain professional tone, provide value at each touchpoint, comply with privacy regulations, and move buyers through the sales pipeline efficiently.', 3
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Property Valuation Methodology', 'Conduct a detailed property valuation for [address] using the [valuation method - comparative sales/income/cost approach]. Analyse recent comparable sales within [radius] focusing on properties with similar characteristics (age, size, condition, location factors). Document property-specific features including land size, building construction, renovation quality, unique attributes, and any detrimental factors. Calculate adjustments for differences in comparable properties, assess current market conditions and trends, incorporate local area analysis, consider vendor motivation and settlement requirements, evaluate rental income potential if applicable, factor in required repairs or improvements, determine realistic price range with supporting evidence, identify optimal marketing strategy and expected timeframe, and provide confidence level in valuation. Include detailed methodology notes and comparable sale evidence for client transparency.', 4
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Contract Review Checklist', 'Create a comprehensive contract review checklist for [property sale/purchase] at [address]. Verify vendor/purchaser details and legal names, confirm property description and title references, review special conditions and their implications, check deposit amount and payment terms, validate settlement date and any time-critical clauses, assess building and pest inspection clauses, review finance approval conditions and timeframes, verify inclusions and exclusions list, check GST implications if applicable, confirm cooling-off period rights, review vendor disclosure statement completeness, identify any easements or encumbrances, verify council and water rates adjustment calculations, check rental income adjustments if tenanted, assess penalty interest clauses, review dispute resolution procedures, confirm solicitor/conveyancer details, identify any unusual or concerning clauses requiring legal advice, and create action items with deadlines for each conditional requirement. Flag high-risk items requiring immediate attention.', 5
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Open Home Planning Protocol', 'Develop a detailed open home plan for [property address] scheduled for [date/time]. Create pre-inspection preparation checklist including property presentation (decluttering, cleaning, styling, repairs), enhance kerb appeal with garden maintenance and entrance staging, set up information station with brochures and contract details, arrange sign-in system with privacy compliance, prepare property highlight tour route, develop engaging property story and key talking points, create FAQ sheet for common questions, set up ambient environment (lighting, temperature, music, fresh flowers), prepare comparable sales data and suburb information, organise refreshments if appropriate, coordinate with vendors regarding pets and personal items, plan traffic flow for multiple visitors, develop safety and security protocols, create follow-up contact capture system, prepare feedback forms, schedule post-inspection debrief with vendors, and develop contingency plans for weather or unexpected issues. Include timeline checklist starting 72 hours before the open home.', 6
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Negotiation Strategy Framework', 'Design a negotiation strategy for [property sale/purchase] at [address] with an asking price of [amount]. Analyse buyer/seller motivation and urgency levels, establish BATNA (Best Alternative To Negotiated Agreement), determine walk-away point and ideal outcome, identify all negotiable elements beyond price (settlement terms, inclusions, conditions, deposit), research comparable recent negotiations in the area, assess current market leverage (buyer vs seller market), prepare positioning statements and value justification, develop concession strategy with pre-planned trade-offs, create anchoring approach for opening position, plan for multiple offer scenarios, prepare response strategies for common tactics (lowball offers, take-it-or-leave-it, time pressure, appeal to emotion), document all offers and counter-offers systematically, maintain professional detachment while building rapport, identify win-win solutions, and establish clear communication protocol. Include decision trees for various negotiation scenarios and pre-planned responses to maintain momentum toward settlement.', 7
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'CRM Management System', 'Establish a comprehensive CRM system for real estate practice managing [number] active clients and [number] properties. Define lead classification categories (hot/warm/cold/nurture), create automated follow-up sequences for each stage, establish data entry standards for contact information, property details, interaction history, and preferences, design pipeline stages from initial enquiry through settlement, set up task automation and reminders, create reporting dashboards for conversion rates and pipeline health, implement lead source tracking for marketing ROI analysis, establish communication templates for each touchpoint, design referral tracking and reward system, create client satisfaction survey workflows, implement post-settlement nurture campaigns, set up birthday and anniversary reminders, establish data privacy compliance procedures, create team collaboration protocols for shared contacts, design integration workflows with property portals and marketing platforms, and establish regular database cleaning and enrichment processes. Include KPI tracking for response times, conversion rates, and client lifetime value.', 8
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Compliance Documentation', 'Develop a compliance documentation system for real estate operations covering [state/territory] regulations. Create verification checklist for agent licensing and registration currency, establish trust account management procedures with reconciliation protocols, document advertising compliance requirements (accurate pricing, licensed agent details, fair trading), create vendor disclosure statement verification process, establish record-keeping system for all transactions (minimum 6-year retention), document cooling-off period disclosure requirements, create conflict of interest declaration procedures, establish underquoting prevention protocols with evidence documentation, create data privacy and GDPR compliance procedures, document required insurance coverage verification, establish continuing professional development tracking, create complaint handling and dispute resolution procedures, document referral fee disclosure requirements, establish auction conduct compliance checklist, and create regular compliance audit schedule. Include templates for all required forms and disclosure documents with automatic update reminders when regulations change.', 9
FROM prompt_packs WHERE name = 'Real Estate Operations';

INSERT INTO prompt_pack_items (pack_id, title, prompt_text, order_index)
SELECT id, 'Investment Analysis Framework', 'Create a comprehensive investment analysis for [property address] at [purchase price]. Calculate gross rental yield based on [weekly/monthly rent], determine net rental yield after all expenses (rates, insurance, strata, maintenance, property management), project capital growth using historical suburb data and future development plans, analyse cash flow with mortgage calculations at [interest rate], calculate loan-to-value ratio and deposit requirements, assess depreciation benefits using quantity surveyor estimates, evaluate tax implications including negative gearing or positive cash flow scenarios, compare investment to alternative properties and asset classes, analyse tenant demand and vacancy risk factors, assess property management requirements and costs, evaluate capital improvements ROI, calculate break-even holding period, determine optimal ownership structure (individual, trust, company), assess exit strategy options and associated costs, evaluate renovation or development potential, and provide sensitivity analysis for interest rate changes and vacancy periods. Include 5 and 10-year projection scenarios with detailed assumptions and risk assessment.', 10
FROM prompt_packs WHERE name = 'Real Estate Operations';