// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krdwypftyokqsffxoobk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZHd5cGZ0eW9rcXNmZnhvb2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3MjU4MzUsImV4cCI6MjA3NzMwMTgzNX0.PcZThTD8TcYa2RJD2vSoHaOSXsfJTjLeUUN0UOg0vbs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});